{
  "hash": "acabd5c6e46a13a731b051c51ac9ca42",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ANOVA y χ²: comparar más de dos grupos\"\nsubtitle: \"Sesión 3 · Parcial 3 · Análisis de Datos II\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 3 · 3.1–3.2 ANOVA · 4.1–4.3 χ²\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n\n\n# Recapitulación {background-color=\"#2C3E50\"}\n\n## Lo que llevamos con [Patricia]{.patricia}\n\n**Sesión 1** — Validamos una afirmación del mercado (\\$1,800 como precio promedio en Roma Norte) con una prueba **t de una muestra**.\n\n**Sesión 2** — Comparamos pares: completo vs. cuarto, superhost vs. no, Roma vs. Condesa — con pruebas **t y de proporciones de dos muestras**.\n\nEn ambos casos comparábamos **dos grupos** (o uno contra una referencia fija).\n\n## Hoy: Patricia tiene una pregunta que no entra en ese molde {.smaller}\n\n> *\"Gracias por las comparaciones. Pero mi decisión real no es Roma vs Condesa: es si mi zona está bien posicionada contra **todas** las alcaldías que estoy considerando. Quiero comparar **Roma Norte, Condesa, Polanco y Del Valle a la vez**. Y de paso: ¿el tipo de propiedad tiene que ver con la zona? Polanco suena a 'puros deptos completos', no sé si eso es real o un prejuicio mío.\"*\n\nDos preguntas, dos herramientas nuevas:\n\n1. Comparar **medias entre 4 grupos** → **ANOVA**\n2. Asociar **dos variables categóricas** (zona × tipo) → **χ²**\n\n## ¿Por qué no simplemente hacer 6 pruebas t? {.smaller}\n\nCon 4 zonas, los pares son: Roma-Condesa, Roma-Polanco, Roma-Del Valle, Condesa-Polanco, Condesa-Del Valle, Polanco-Del Valle → **6 pruebas**.\n\n::: {.callout-important}\n**Problema del error tipo I inflado.** Si cada t-test usa $\\alpha = 0.05$, la probabilidad de que al menos *una* de las 6 pruebas dé un \"falso positivo\" es mucho mayor que 0.05. Aproximadamente:\n\n$$1 - (1 - 0.05)^6 \\approx 0.26$$\n\nUn 26% de probabilidad de declarar \"significativa\" una diferencia inexistente. Inaceptable.\n:::\n\nEl **ANOVA** resuelve esto: una sola prueba con un solo $\\alpha$, que pregunta *\"¿hay alguna diferencia entre los grupos?\"*. Si la respuesta es sí, después (y solo después) investigamos *cuáles pares*.\n\n# ANOVA unidireccional {background-color=\"#18BC9C\"}\n\n## La intuición del ANOVA {.smaller}\n\nEl ANOVA compara **dos fuentes de variación**:\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Varianza entre grupos**\nQué tan distintas son las medias de los grupos entre sí.\n\nSi las zonas tuvieran precios muy diferentes, esta varianza sería grande.\n:::\n::: {.column width=\"50%\"}\n**Varianza dentro de grupos**\nQué tanto varían los precios *dentro* de cada zona.\n\nEs el \"ruido de fondo\" natural de cada mercado.\n:::\n:::\n\n<br>\n\nEl estadístico **F** es, conceptualmente, un cociente:\n\n$$F = \\frac{\\text{Varianza ENTRE grupos}}{\\text{Varianza DENTRO de grupos}}$$\n\nSi F es grande, las diferencias entre zonas son grandes *comparadas con el ruido*. Eso es evidencia de que al menos una zona difiere.\n\n## Las hipótesis\n\n$$H_0: \\; \\mu_{\\text{Roma}} = \\mu_{\\text{Condesa}} = \\mu_{\\text{Polanco}} = \\mu_{\\text{Del Valle}}$$\n$$H_1: \\; \\text{al menos una media difiere de las demás}$$\n\n::: {.callout-note}\nOjo al planteo de $H_1$: **no** dice \"todas son diferentes\" ni especifica cuál. Solo dice \"no todas son iguales\". Decir cuáles pares difieren es un segundo paso (post-hoc).\n:::\n\n## Los datos de las 4 zonas {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nzonas <- c(\"Roma Norte\", \"Condesa\", \"Polanco\", \"Del Valle\")\n\nd <- listings |>\n  filter(host_neighbourhood %in% zonas) |>\n  mutate(host_neighbourhood = factor(host_neighbourhood,\n                                     levels = zonas))\n\nd |>\n  group_by(host_neighbourhood) |>\n  summarise(\n    n       = n(),\n    media   = mean(price),\n    mediana = median(price),\n    de      = sd(price)\n  )\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Zona       |     n| Media| Mediana| Desv. est.|\n|:----------|-----:|-----:|-------:|----------:|\n|Roma Norte | 1,183| 1,898|   1,386|      2,971|\n|Condesa    |   762| 1,953|   1,206|      2,698|\n|Polanco    | 1,504| 2,396|   1,728|      2,935|\n|Del Valle  |   163| 1,039|     879|        909|\n\n\n:::\n:::\n\n\n\n:::\n\n## Una nota rápida sobre las etiquetas {.smaller}\n\nEl campo `host_neighbourhood` es **texto libre declarado por el host**. Además de los nombres limpios existen variantes menores (`Roma norte`, `ROMA NORTE`, `Hipódromo Condesa`). Para mantener el análisis reproducible en una sola línea de filtro, **no las consolidamos**: usamos solo los cuatro nombres con la ortografía exacta.\n\n::: {.callout-note appearance=\"minimal\"}\nDecisión metodológica que conviene declarar al reportar: \"trabajamos con los listings cuyo `host_neighbourhood` coincide exactamente con Roma Norte, Condesa, Polanco o Del Valle; las variantes ortográficas (~3%) se excluyen\". Esto no sesga materialmente los resultados, pero es parte del *qué hicimos y qué no* que siempre se reporta.\n:::\n\n## Distribución por zona {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nd |>\n  ggplot(aes(x = host_neighbourhood, y = price,\n             fill = host_neighbourhood)) +\n  geom_boxplot(alpha = 0.7, outlier.alpha = 0.25) +\n  scale_y_continuous(labels = label_comma(),\n                     limits = c(0, 6000)) +\n  scale_fill_manual(values = c(\"#18BC9C\", \"#3498DB\",\n                               \"#F39C12\", \"#E74C3C\")) +\n  labs(x = NULL, y = \"Precio (MXN por noche)\",\n       title = \"Precio por zona\") +\n  theme(legend.position = \"none\")\n```\n:::\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03_anova_chi2_files/figure-revealjs/unnamed-chunk-2-1.png){width=864}\n:::\n:::\n\n\n\n:::\n\n## Verificando supuestos {.smaller}\n\nEl ANOVA clásico asume **varianzas iguales entre grupos**. Veamos:\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nd |>\n  group_by(host_neighbourhood) |>\n  summarise(\n    n  = n(),\n    de = sd(price)\n  )\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Zona       |     n| Desv. est.|\n|:----------|-----:|----------:|\n|Roma Norte | 1,183|      2,971|\n|Condesa    |   762|      2,698|\n|Polanco    | 1,504|      2,935|\n|Del Valle  |   163|        909|\n\n\n:::\n:::\n\n\n\n:::\n\nDel Valle tiene una desviación estándar **~3 veces menor** que Polanco o Roma Norte. El supuesto no se cumple.\n\n::: {.callout-important}\n**Usamos Welch ANOVA por default.** Es el análogo multi-grupo del Welch t-test de S2: robusto ante varianzas desiguales. En R: `oneway.test(..., var.equal = FALSE)`.\n:::\n\n## Ejecución: Welch ANOVA {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\noneway.test(\n  price ~ host_neighbourhood,\n  data      = d,\n  var.equal = FALSE\n)\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  price and host_neighbourhood\nF = 59.806, num df = 3.0, denom df = 1090.7, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n:::\n\n**F = 59.8**, p-valor ≈ <1e-16. Rechazamos $H_0$: al menos una zona difiere. **Pero el F global no nos dice cuál.**\n\n## ¿Qué pares difieren? Tukey HSD {.smaller}\n\nDespués de un ANOVA significativo, usamos un **post-hoc** para identificar los pares. El más común es **Tukey HSD**, que ajusta los p-valores para controlar el error tipo I a lo largo de las 6 comparaciones.\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nm <- aov(price ~ host_neighbourhood, data = d)\nTukeyHSD(m)\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Par                  | Dif. (MXN)| IC inf.| IC sup.| p ajust.|\n|:--------------------|----------:|-------:|-------:|--------:|\n|Condesa-Roma Norte   |         55|    -283|     394|        1|\n|Polanco-Roma Norte   |        498|     215|     782|        0|\n|Del Valle-Roma Norte |       -859|  -1,469|    -250|        0|\n|Polanco-Condesa      |        443|     118|     767|        0|\n|Del Valle-Condesa    |       -914|  -1,544|    -285|        0|\n|Del Valle-Polanco    |     -1,357|  -1,959|    -756|        0|\n\n\n:::\n:::\n\n\n\n:::\n\n::: {.callout-note appearance=\"minimal\"}\nTukey HSD asume varianzas iguales. Con heterocedasticidad moderada sus p-valores son aproximaciones razonables; el análogo formal es Games-Howell. Para una lectura de negocios, los patrones de \"significativo vs. no\" coinciden casi siempre.\n:::\n\n## Lectura de negocio de Tukey {.smaller}\n\n::: {.callout-note}\n**Recomendación preliminar para Patricia.**\n\nSobre 3,612 listings al corte de 28 de septiembre de 2025:\n\n- **Roma Norte (~\\$1,898) y Condesa (~\\$1,953) son estadísticamente indistinguibles** en precio medio (p ajustado = ). Tu vecina y tú estamos en el mismo mercado.\n- **Polanco (~\\$2,396) es más cara que Roma Norte** por ≈ \\$ MXN/noche (significativo).\n- **Del Valle (~\\$1,039) es más barata que Roma Norte** por ≈ \\$ MXN/noche (significativo).\n- Tu posición en el \"ranking de precio medio\": **#2 de 4**, empatada con Condesa, detrás de Polanco.\n:::\n\n## Lo que ANOVA **no** le dice a Patricia {.smaller}\n\n::: {.callout-important}\n- **No dice que \"estar en Polanco haría su depto más caro\"**. Podría ser que las propiedades en Polanco sean *sistemáticamente distintas* (más grandes, mejor amuebladas, mejor ubicadas). La asociación zona-precio no es necesariamente causal.\n- **No dice nada sobre la ocupación**. Puede ser que Polanco cobre más pero se ocupe menos. El *ingreso* es precio × ocupación, y esa cuenta la veremos más adelante.\n- **No dice nada sobre SU propiedad específica.** Son promedios de mercado.\n\nLa diferencia entre \"asociación\" y \"causa\" es el tema central que retomaremos en la S6 (regresión simple III) y la S7 (múltiple).\n:::\n\n# ANOVA bidireccional — extensión {background-color=\"#F39C12\"}\n\n## Cuando dos factores actúan a la vez {.smaller}\n\nHasta ahora: un factor (zona). Pero en la realidad, el precio depende de **varios factores simultáneamente**. El ANOVA **bidireccional** (o *factorial*) es la extensión natural para **dos factores categóricos** a la vez.\n\nTres preguntas que responde:\n\n1. ¿Hay efecto del **factor A** (zona)?\n2. ¿Hay efecto del **factor B** (tipo de habitación)?\n3. ¿Hay **interacción**? Es decir, ¿el efecto del tipo de habitación *depende* de la zona?\n\n::: {.callout-note appearance=\"minimal\"}\n**Intuición de la interacción.** \"En Polanco el premio por rentar completo es \\$X; en Del Valle el premio es \\$Y. Si X ≠ Y, hay interacción — el efecto de un factor depende del nivel del otro.\"\n:::\n\n## Cómo se ve en R (conceptual) {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\naov(\n  price ~ host_neighbourhood * room_type,\n  data = d |>\n    filter(room_type %in%\n           c(\"Entire home/apt\", \"Private room\"))\n) |> summary()\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                               Df    Sum Sq   Mean Sq F value   Pr(>F)    \nhost_neighbourhood              3 3.534e+08 117798974  15.010 1.04e-09 ***\nroom_type                       1 7.924e+08 792402614 100.970  < 2e-16 ***\nhost_neighbourhood:room_type    3 3.314e+07  11045359   1.407    0.239    \nResiduals                    3556 2.791e+10   7847923                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: {.callout-note appearance=\"minimal\"}\nNo calculamos F ni sumas de cuadrados a mano — el mensaje para S3 es **que existen modelos factoriales y que la sintaxis en R es mínima**. Cuando lleguemos a regresión múltiple (S7) retomaremos esta lógica con variables continuas.\n:::\n\n# χ² — bondad de ajuste {background-color=\"#2C3E50\"}\n\n## Cambio de escenario {.smaller}\n\nHasta ahora: pruebas sobre **medias** (números continuos). Ahora: pruebas sobre **proporciones** y **composiciones** (categorías).\n\n**Bondad de ajuste** responde: *\"¿la distribución observada en una variable categórica se apega a una distribución de referencia?\"*\n\nEs el análogo categórico del artículo de S1 (\\$1,800): una afirmación publicada, un dato nuestro, una prueba.\n\n## Caso: el mix de Roma Norte {.smaller}\n\nUn reporte de mercado publicado antes del corte actual afirmaba que en Roma Norte el mix era:\n\n- **70%** propiedad completa (`Entire home/apt`)\n- **30%** el resto (cuartos privados, hoteles, etc.)\n\nPregunta: ¿se apega la realidad del corte de 28 de septiembre de 2025?\n\n$$H_0: \\; p_{\\text{Entire}} = 0.70, \\; p_{\\text{No Entire}} = 0.30$$\n$$H_1: \\; \\text{al menos una proporción difiere}$$\n\n## Ejecución {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nrn <- d |>\n  filter(host_neighbourhood == \"Roma Norte\") |>\n  mutate(tipo = if_else(room_type == \"Entire home/apt\",\n                        \"Entire\", \"No_Entire\"))\n\nobs_rn <- table(rn$tipo)\nobs_rn\n\nchisq.test(obs_rn, p = c(0.70, 0.30))\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nObservado en Roma Norte:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Entire No_Entire \n      983       200 \n```\n\n\n:::\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  obs_rn\nX-squared = 96.583, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n:::\n\n**Lectura**: la proporción observada es **83% Entire**, bastante por encima del 70% que afirmaba el reporte. p-valor ≈ <1e-16 → **rechazamos la afirmación**. El mercado de Roma Norte está más concentrado en propiedad completa de lo que decía la referencia.\n\n# χ² — contingencia {background-color=\"#18BC9C\"}\n\n## La pregunta de Patricia {.smaller}\n\n> *\"¿El tipo de propiedad se relaciona con la zona? ¿Polanco es más 'depto completo' que Roma Norte?\"*\n\nFormalmente:\n\n$$H_0: \\; \\text{tipo y zona son independientes}$$\n$$H_1: \\; \\text{hay asociación entre tipo y zona}$$\n\n::: {.callout-note appearance=\"minimal\"}\n**Consolidación necesaria.** `Hotel room` y `Shared room` tienen conteos muy bajos — haría que χ² emita advertencias por celdas esperadas < 5. Colapsamos a **dos categorías**: `Entire` vs. `No_Entire`. Esto además hace la interpretación más directa.\n:::\n\n## Tabla observada {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nd2 <- d |>\n  mutate(tipo = if_else(room_type == \"Entire home/apt\",\n                        \"Entire\", \"No_Entire\"))\n\ntbl <- table(d2$host_neighbourhood, d2$tipo)\ntbl\n\n# Proporción de \"Entire\" por zona\nprop.table(tbl, margin = 1) |> round(3)\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nConteos observados:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n             Entire No_Entire\n  Roma Norte    983       200\n  Condesa       489       273\n  Polanco      1274       230\n  Del Valle      97        66\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProporción por zona (fila):\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n             Entire No_Entire\n  Roma Norte  0.831     0.169\n  Condesa     0.642     0.358\n  Polanco     0.847     0.153\n  Del Valle   0.595     0.405\n```\n\n\n:::\n:::\n\n\n\n:::\n\n## Ejecución {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nchi_cont <- chisq.test(tbl)\nchi_cont\n\n# Verificar que todas las celdas esperadas sean ≥ 5\nchi_cont$expected |> round(1)\n```\n\n## 📊 Resultado\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  tbl\nX-squared = 177.8, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nValores esperados (todos ≥ 5, supuesto OK):\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n             Entire No_Entire\n  Roma Norte  931.1     251.9\n  Condesa     599.8     162.2\n  Polanco    1183.8     320.2\n  Del Valle   128.3      34.7\n```\n\n\n:::\n:::\n\n\n\n:::\n\n**X² = 177.8**, df = 3, p ≈ <1e-16.\n\n## Lectura de negocio {.smaller}\n\n::: {.callout-note}\n**Recomendación para Patricia.**\n\nLa composición del mercado **sí depende de la zona** (χ² ≈ 177.8, p ≈ <1e-16).\n\n- **Polanco (85%) y Roma Norte (83%)** están dominadas por propiedad completa. Tu producto es el *formato mainstream* de tu zona.\n- **Condesa (64%) y Del Valle (60%)** tienen mezclas más diversas, con presencia relevante de cuartos privados.\n\n**Implicación directa para ti**: listar el depto completo en Roma Norte no es un posicionamiento diferenciador — es el estándar. Eso significa que competirás con muchos otros deptos completos, y que la diferenciación tendrá que venir de atributos más finos (tamaño, amenidades, fotos, reseñas), no del formato.\n:::\n\n## Lo que χ² **no** le dice a Patricia {.smaller}\n\n::: {.callout-important}\n- **No dice nada sobre los precios dentro de cada celda.** Solo dice \"la composición del mercado es distinta\". El ANOVA (de hace 20 min) es el que habla de precio.\n- **No dice qué factor causa qué.** Si Polanco tiene más \"Entire\", no sabemos si es porque los hosts de Polanco eligen ese formato, o porque los cuartos privados en esa zona son inviables como negocio (diferencias estructurales del edificio, perfil del huésped, etc.).\n- **No dice nada sobre las categorías que colapsamos.** La estructura fina dentro de \"No_Entire\" (cuántos son cuartos, cuántos hoteles) queda oculta en esa tabla. Si eso importara para una decisión, habría que rehacer el análisis con otra segmentación.\n:::\n\n# Actividad para notebook {background-color=\"#2C3E50\"}\n\n## Lo que harán en su notebook {.smaller}\n\nRepliquen el análisis en su propio `.ipynb`:\n\n1. Filtrar las 4 zonas desde el csv crudo.\n2. Boxplot comparativo de precio por zona.\n3. Ejecutar Welch ANOVA y Tukey HSD.\n4. Construir la tabla 4×2 de zona × (Entire / No_Entire) y correr χ².\n5. Redactar **un solo párrafo profesional** (máximo 150 palabras) que resuma los dos hallazgos para Patricia, incluyendo al menos una advertencia honesta sobre lo que el análisis NO puede concluir.\n\n# Cierre {background-color=\"#18BC9C\"}\n\n## Lo que llevan hoy {.smaller}\n\n1. Cuando hay **más de dos grupos** a comparar, la herramienta correcta no es \"varios t-tests\" (inflación de α) sino **ANOVA**.\n2. El **Welch ANOVA** es el default razonable cuando las varianzas no son iguales — consistente con el criterio de S2.\n3. Un ANOVA global significativo requiere un **post-hoc (Tukey HSD)** para identificar los pares que difieren.\n4. El **χ² de bondad de ajuste** contrasta una distribución categórica observada contra una de referencia.\n5. El **χ² de contingencia** prueba independencia entre dos variables categóricas. Es el análogo categórico de lo que hicimos en S1 y S2 con medias y proporciones.\n\n## Para la próxima sesión {.smaller}\n\nPatricia ya sabe:\n\n- **Dónde** el mercado tiene precios distintos (ANOVA).\n- **Cómo se distribuye** la oferta entre tipos y zonas (χ²).\n\nLo que le falta es el paso más concreto: **cuánto cobrar específicamente por su depto**. Para eso ya no basta con comparar grupos — necesita un *modelo* que traduzca características de una propiedad en un precio esperado.\n\n**Sesión 4: regresión lineal simple — del problema al modelo.**\n",
    "supporting": [
      "03_anova_chi2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}