{
  "hash": "2b5d6e5e2d207f72f3611048235841e4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión múltiple I: construcción y 'controlando por'\"\nsubtitle: \"Sesión 7 · Parcial 3 · Análisis de Datos II\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 7 · 6.1 Construcción · 6.2 Controlando por · 6.3 Variables categóricas\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Recapitulación + pregunta de Patricia {background-color=\"#2C3E50\"}\n\n## Lo que dejamos abierto en S6 {.smaller}\n\nS6 cerró con dos historias compatibles que el modelo simple **no podía distinguir**:\n\n::: {.incremental}\n- **Historia A**: el huésped paga por **espacio físico** (más recámaras → más espacio → más valor).\n- **Historia B**: el huésped paga por **capacidad** (más camas → más gente → más valor por noche).\n:::\n\n`bedrooms` y `accommodates` correlacionan a **0.88** en Roma Norte. Con un solo modelo de una variable, era imposible separar A de B.\n\n## La pregunta de [Patricia]{.patricia} hoy {.smaller}\n\n> *\"Un solo factor no alcanza. Sus mismos datos me sugirieron que recámaras puede ser sólo un proxy de algo más. Quiero estimar el precio **controlando por varias cosas a la vez** — y entender qué variables vale la pena meter al modelo y cuáles no.\"*\n\n::: {.callout-note}\nHoy entramos al modelo lineal **múltiple**. La sintaxis cambia poco. La interpretación cambia mucho.\n:::\n\n# Mecánica del modelo múltiple {background-color=\"#18BC9C\"}\n\n## Sintaxis: del simple al múltiple {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\n# Simple (S5)\nmodelo_simple <- lm(price ~ bedrooms,\n                    data = roma)\n\n# Múltiple (S7) — agregar variables con `+`\nmodelo <- lm(price ~ bedrooms + accommodates,\n             data = roma)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|             | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:------------|--------:|----------:|-------:|------------------:|\n|(Intercept)  | -424.101|     80.006|  -5.301|                  0|\n|bedrooms     |  835.276|     77.906|  10.722|                  0|\n|accommodates |  254.926|     35.261|   7.230|                  0|\n\n\n:::\n:::\n\n\n:::\n\nCada variable adicional agrega un coeficiente. Todo lo que sabemos del summary (estimación, SE, t, p-valor) sigue válido — ahora aplicado a varias variables simultáneamente.\n\n## \"Controlando por\" — qué significa exactamente {.smaller}\n\nEl coeficiente de `bedrooms` cambia entre el modelo simple y el múltiple:\n\n| Modelo | β_bedrooms | Lectura |\n|---|---|---|\n| Simple `~ bedrooms` | \\$1,329 | \"Comparando deptos que difieren en una recámara, sin condicionar nada\" |\n| Múltiple `~ bedrooms + accommodates` | \\$835 | \"Comparando deptos que difieren en una recámara **pero tienen la misma capacidad**\" |\n\n::: {.callout-warning appearance=\"minimal\"}\nEsa condición — *\"manteniendo constante la capacidad\"* — **es** \"controlando por\". El modelo le pide a R: *\"dame el efecto único de bedrooms una vez que ya consideré el efecto de accommodates\"*.\n:::\n\n# Resolución de las dos historias {background-color=\"#2C3E50\"}\n\n## ¿Qué le pasó a β_bedrooms? {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Modelo                 | β bedrooms (MXN/recámara)| β accommodates (MXN/persona)|\n|:----------------------|-------------------------:|----------------------------:|\n|M1: solo bedrooms (S5) |                     1,329|                            —|\n|M2: + accommodates     |                       835|                          255|\n\n\n:::\n:::\n\n\n::: {.incremental}\n- El efecto de bedrooms **bajó 37%** al meter accommodates.\n- **Pero no se anuló.** Recámaras siguen pesando, sólo que menos de lo que parecía.\n- accommodates aporta ~\\$255 por persona adicional, manteniendo recámaras constantes.\n:::\n\n## El veredicto sobre las dos historias {.smaller}\n\n::: {.callout-note}\n**Ninguna historia es pura. Las dos son parcialmente verdaderas.**\n\n- Una recámara adicional, *con la misma capacidad*, sigue valiendo ~\\$835 MXN/noche.\n- Una persona adicional de capacidad, *con las mismas recámaras*, vale ~\\$255 MXN/noche.\n\nEl efecto bruto que veíamos en S5 (\\$1,329) era una **combinación** de ambos. El modelo múltiple los separa.\n:::\n\n## Aplicación a [Patricia]{.patricia} con cap = 4 {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\npredict(modelo,\n        newdata = data.frame(\n          bedrooms     = 2,\n          accommodates = 4))\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   1 \n2266 \n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-note appearance=\"minimal\"}\nLa predicción para Patricia con M2 es **\\$2,266 MXN/noche** — distinta de la S6 porque ahora condicionamos en una capacidad específica (4 personas).\n:::\n\n# El costo del acoplamiento {background-color=\"#E74C3C\"}\n\n## ¿Mejoró el modelo al agregar accommodates? {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Métrica                | M1: simple| M2: + accommodates|\n|:----------------------|----------:|------------------:|\n|R²                     |      0.551|              0.574|\n|R² ajustada            |      0.550|              0.573|\n|RSE (MXN)              |      1,318|              1,285|\n|SE de β_bedrooms (MXN) |         38|                 78|\n|Ancho del PI 95% (MXN) |      5,176|              5,046|\n\n\n:::\n:::\n\n\n::: {.incremental}\n- R² subió **solo 2.3 puntos porcentuales**.\n- RSE bajó solo \\$33.\n- **El ancho del intervalo de predicción se redujo solo 3%.**\n- **El SE de β_bedrooms se infló 2.03×.**\n:::\n\n## ¿Por qué tan poca mejora? {.smaller}\n\n`bedrooms` y `accommodates` correlacionan a **0.88**. Contienen información **muy redundante**.\n\n::: {.incremental}\n- El modelo no puede decidir cuánto del precio \"le toca\" a cada una.\n- Esa indecisión se manifiesta como **menos precisión** en cada coeficiente individual.\n- Pero la información combinada **no es mucho más** que la de cualquiera de las dos por separado.\n:::\n\n::: {.callout-warning}\n**Más variables ≠ mejor modelo.** Cuando una variable nueva es altamente redundante con las que ya tenemos, su aporte predictivo es marginal y aumenta el error estándar de los coeficientes existentes.\n:::\n\n## La lección operativa para selección {.smaller}\n\n::: {.callout-important}\nEl criterio NO es *\"agreguemos todo lo que se pueda\"*.\n\nEl criterio ES *\"agreguemos variables que aporten información que las existentes no contienen\"*.\n\n¿Cómo se ve eso en la práctica? Necesitamos una variable **no correlacionada** con bedrooms ni con accommodates. Tenemos una candidata limpia: **superhost**.\n:::\n\n# Una variable que sí aporta {background-color=\"#18BC9C\"}\n\n## El dummy `superhost` — tie-back a S2 {.smaller}\n\nEn **S2** comparamos directamente las medias de precio entre superhosts y no-superhosts (t-test):\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\nt.test(price ~ superhost, data = roma)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nDiferencia de medias: 368 MXN\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstadístico t = -2.48, p-valor = 0.013\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n¿Rechaza H0 al 5%? Sí\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-note appearance=\"minimal\"}\n**S2 concluyó**: la diferencia es positiva (~\\$368) pero estadísticamente significativa.\n:::\n\n## Sintaxis para variables categóricas {.smaller}\n\n`lm()` acepta variables tipo `factor` directamente — convierte automáticamente a dummies.\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\nroma <- roma |>\n  mutate(superhost = factor(host_is_superhost,\n                            levels = c(FALSE, TRUE),\n                            labels = c(\"No\", \"Sí\")))\n\nmodelo <- lm(price ~ bedrooms + accommodates + superhost,\n             data = roma)\nsummary(modelo)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|             | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:------------|--------:|----------:|-------:|------------------:|\n|(Intercept)  | -573.558|    105.442|  -5.440|              0.000|\n|bedrooms     |  861.941|     98.936|   8.712|              0.000|\n|accommodates |  268.693|     46.197|   5.816|              0.000|\n|superhostSí  |  137.473|     96.919|   1.418|              0.156|\n\n\n:::\n:::\n\n\n:::\n\nR nombra el coeficiente como `superhostSí` — significa \"el efecto de pasar de **No** a **Sí**, manteniendo todo lo demás constante\".\n\n## El giro: la conclusión cambia al controlar {.smaller}\n\n| Análisis | Diferencia | p-valor | Conclusión |\n|---|---|---|---|\n| t-test bivariado (S2) | \\$368 | 0.013 | Significativo |\n| β en M3 (controlando size) | \\$137 | 0.156 | NO significativo al 5% |\n\n::: {.callout-important}\n**El efecto de superhost se vuelve más detectable al controlar por tamaño.** Sin controlar, la variabilidad por bedrooms y accommodates **ahogaba la señal**. Una vez que el modelo \"explica\" parte de esa variabilidad, el efecto puro de superhost emerge.\n\nEsto es exactamente lo que \"controlar por\" puede hacer — no solo cambia magnitud, también detectabilidad.\n:::\n\n## Aplicación a [Patricia]{.patricia}: dos escenarios {.smaller}\n\nPatricia es host **nuevo**. La certificación de superhost requiere historial — la considera un **objetivo aspiracional** para su primer año.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Escenario                      | Predicción| PI 95% (truncado, MXN)|\n|:------------------------------|----------:|----------------------:|\n|Sin superhost (estado inicial) |      2,225|            [0 , 4,719]|\n|Con superhost (objetivo)       |      2,363|            [0 , 4,854]|\n\n\n:::\n:::\n\n\n::: {.callout-note}\n**Premium estimado por superhost: ~\\$137 MXN/noche** (≈ 6% sobre la base).\n\nInformación concreta para evaluar el costo-beneficio de la certificación: cumplir con tasa de respuesta, mantener tasa de aceptación, evitar cancelaciones.\n:::\n\n# Selección de variables + cierre {background-color=\"#2C3E50\"}\n\n## R² ajustada como orientación, no regla {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Modelo             |    R²| R² ajustada|\n|:------------------|-----:|-----------:|\n|M1: solo bedrooms  | 0.551|       0.550|\n|M2: + accommodates | 0.574|       0.573|\n|M3: + superhost    | 0.606|       0.604|\n\n\n:::\n:::\n\n\n::: {.callout-warning appearance=\"minimal\"}\nLa R² ajustada **penaliza** agregar variables. Pero NO es un veredicto absoluto: una variable que apenas mejora R² ajustada puede ser indispensable si el objetivo es **interpretar un efecto** (entonces queremos controlar por confusores aunque no nos ayuden a predecir).\n:::\n\n## Tres criterios humanos para elegir variables {.smaller}\n\n::: {.incremental}\n1. **Relevancia teórica** — ¿hay razón para creer que la variable afecta el precio? Si sí, considérala. Si no, ignórala.\n2. **No redundancia** — si correlaciona >0.85 con otra ya incluida, su aporte es marginal y costoso.\n3. **Interpretabilidad** — si el coeficiente no tiene una historia clara, la variable es difícil de comunicar a Patricia.\n:::\n\n::: {.callout-note appearance=\"minimal\"}\nLa regresión múltiple **no es búsqueda automática** (stepwise / AIC / lasso). Es **construcción de juicio**. La pregunta operativa correcta no es \"¿qué variables maximizan R²?\" sino \"¿qué variables hacen al modelo más útil para mi decisión?\".\n:::\n\n## Lo que este modelo NO le dice a [Patricia]{.patricia} {.smaller}\n\n::: {.callout-important}\n- **El intervalo de predicción sigue ancho** (~\\$4,987 de ancho). Hay heterogeneidad real entre deptos individuales que ningún modelo simple captura.\n- **No hemos diagnosticado los supuestos** del modelo múltiple. ¿Linealidad y homocedasticidad se mantienen? ¿La inclusión de variables correlacionadas tiene consecuencias técnicas? Eso es S8.\n- **No es causalidad establecida**. Aunque controlamos por capacidad, hay variables no medidas (m², ubicación específica, calidad de fotos, reseñas) que pueden estar moviendo el precio.\n- **`accommodates` con cor 0.88** está al borde de lo que muchos textos rechazarían por redundancia. Decisión deliberada para esta sesión: lo mantenemos para ilustrar el costo del acoplamiento; en S8 evaluamos si quedarnos con M3 o simplificar.\n:::\n\n## Entrega ejecutiva a [Patricia]{.patricia} {.smaller}\n\n::: {.callout-note appearance=\"minimal\"}\n**Para su depto de 2 recámaras / 4 personas en Roma Norte:**\n\n- Las dos historias de S6 son ambas parciales. Recámaras Y capacidad pesan: separar sus efectos requirió controlar por ambas.\n- **Premium estimado por certificación de superhost: ~\\$137 MXN/noche** (≈ 6% sobre la base). Es palanca real con efecto comprobado.\n- **Predicción base (sin superhost):** ~\\$2,225 MXN/noche. **Aspiracional (con superhost):** ~\\$2,363.\n- **Recomendación operativa**: buscar la certificación de superhost vale la pena. Sobre las recámaras: sin reformas no podemos cambiarlo, pero la capacidad sí podría aumentarse marginalmente (sofá-cama, literas) capturando parte del efecto que el modelo atribuye a accommodates.\n- **Lo que falta:** diagnóstico del modelo y caso integrador final. Eso es la próxima sesión.\n:::\n\n# Actividad para notebook {background-color=\"#18BC9C\"}\n\n## Lo que harán en su notebook {.smaller}\n\nRepliquen y extiendan el análisis:\n\n1. Cargar `modelo_s05.rds` (o reconstruirlo). Verificar continuidad con S5.\n2. Construir M1, M2, M3 incrementalmente.\n3. Producir la tabla comparativa: β_bedrooms, R², RSE, SE de β_bedrooms y ancho de PI por modelo.\n4. Identificar y comentar el cambio de β_bedrooms al pasar de M1 a M2.\n5. Calcular `predict()` con `interval = \"prediction\"` para Patricia en M3 (con y sin superhost).\n6. Reproducir el t-test bivariado de S2 para superhost y compararlo con el coeficiente en M3.\n7. Redactar la **entrega ejecutiva** (≈250 palabras) con:\n   - Resolución de las dos historias\n   - Premium estimado por superhost\n   - Recomendación sobre la certificación\n\n# Próxima sesión {background-color=\"#2C3E50\"}\n\n## Lo que llevan hoy {.smaller}\n\n1. **Sintaxis múltiple**: `lm(y ~ x1 + x2 + ...)`. Cada `+` agrega un coeficiente.\n2. **\"Controlando por\"** = \"comparando con TODAS las demás variables iguales\".\n3. **Las dos historias eran ambas parciales** — separar requiere modelar las dos juntas.\n4. **Más variables ≠ mejor modelo**: agregar variables redundantes infla SEs sin mejorar predicción.\n5. **El efecto de una variable puede emerger al controlar** por confusores (caso superhost).\n6. **Selección de variables es juicio**, no algoritmo: relevancia + no redundancia + interpretabilidad.\n\n## Sesión 8 — Regresión múltiple II {.smaller}\n\n> *\"Entrega final: un modelo que pueda defender y una recomendación concreta sobre cómo listar.\"*\n\n::: {.incremental}\n- **Diagnóstico** del modelo múltiple: ¿se cumplen los supuestos cuando hay variables correlacionadas?\n- **Identificación formal** del problema de redundancia (lo que llevamos viendo conductualmente).\n- **Caso integrador**: el modelo definitivo de la consultora para Patricia.\n- **Defensa de la recomendación** ante la cliente.\n:::\n\n**Sesión 8: Regresión múltiple II — diagnóstico, interpretación, caso integrador.**\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}