{
  "hash": "738f68a375a76252bf759a81432f9569",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión múltiple II: diagnóstico, interpretación y caso integrador\"\nsubtitle: \"Sesión 8 · Parcial 3 · Análisis de Datos II · Cierre del semestre\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 8 · 6.4 Diagnóstico · 6.5 Multicolinealidad · 6.6 Caso integrador\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Recap + estructura del cierre {background-color=\"#2C3E50\"}\n\n## Lo que llevamos con [Patricia]{.patricia} {.smaller}\n\n**Sesiones 1-3** — Pruebas: t una muestra · t/z dos muestras · ANOVA · χ². Aprendimos a comparar grupos.\n\n**Sesiones 4-6** — Modelo simple. Construcción · auditoría con depuración del atípico de \\$81k · interpretación con CI vs PI · sembrar causalidad.\n\n**Sesión 7** — Modelo múltiple. Resolvimos las dos historias (β_bedrooms cae 35% al controlar por capacidad). Vimos el costo del acoplamiento sin nombrarlo.\n\n::: {.callout-note}\n**Hoy** — Cerramos el ciclo. Auditamos M3, formalizamos la conversación de redundancia entre variables, decidimos el modelo final, y entregamos a Patricia la recomendación profesional.\n:::\n\n## La pregunta más decisiva de [Patricia]{.patricia} {.smaller}\n\n> *\"Entrega final: necesito un modelo que pueda **defender** y una recomendación **concreta** sobre cómo listar el departamento. Quiero saber qué tan en serio puedo tomar los rangos que me dieron. Y quiero un memo que pueda llevar a mi asesor financiero.\"*\n\n::: {.callout-warning appearance=\"minimal\"}\nLa pregunta no es solo \"¿cuánto?\". Es **\"¿qué tan en serio puedo tomar lo que me das?\"**. Esa es la pregunta que cierra cualquier proyecto de consultoría seria.\n:::\n\n## Estructura del cierre {.smaller}\n\nCuatro preguntas que hoy resolvemos:\n\n1. **¿M3 es internamente coherente?** → diagnóstico de supuestos\n2. **¿La redundancia entre `bedrooms` y `accommodates` es problemática?** → multicolinealidad y VIF\n3. **¿M3 es la mejor elección?** → comparación de candidatos\n4. **¿Qué entregamos a Patricia?** → caso integrador y memo final\n\n# Diagnóstico de supuestos en M3 {background-color=\"#18BC9C\"}\n\n## Los 4 supuestos releídos para múltiple {.smaller}\n\n| Supuesto | Cómo se ve en múltiple |\n|---|---|\n| Linealidad | El ajustado depende de varias variables — la línea LOWESS lee la combinación |\n| Homocedasticidad | La varianza no debe crecer con el ajustado (que es un compuesto) |\n| Independencia | Cada listing es un anuncio distinto — sigue asumido |\n| Normalidad | Q-Q sobre los residuos del modelo |\n\n::: {.callout-note appearance=\"minimal\"}\nA diferencia de S5 (donde `bedrooms` discreta producía bandas verticales), aquí los plots se ven más como nubes continuas — el ajustado combina las 3 variables.\n:::\n\n## Plot 1 — Residuals vs Fitted {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 1)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08_regresion_multiple_2_files/figure-revealjs/unnamed-chunk-1-1.png){width=864}\n:::\n:::\n\n\n:::\n\n**Qué buscamos.** Línea LOWESS plana sobre cero (linealidad) y dispersión similar a lo largo del eje (homocedasticidad).\n\n**Qué encontramos.** Linealidad razonable, pero la **dispersión crece notablemente con el valor ajustado** — heterocedasticidad clara.\n\n## Heterocedasticidad cuantificada {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08_regresion_multiple_2_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n::: {.callout-warning}\n**cor = 0.552 es violación severa.** Implicación: los IC y PI formales **subestiman la incertidumbre real**. La banda razonable de incertidumbre es probablemente más amplia que la que el modelo reporta.\n:::\n\n## Plot 2 — Q-Q (normalidad) {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 2)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08_regresion_multiple_2_files/figure-revealjs/unnamed-chunk-3-1.png){width=864}\n:::\n:::\n\n\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAsimetría residual: 2.52  (debe ser ~0)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKurtosis exceso:    17.80  (debe ser ~0 para normal)\n```\n\n\n:::\n:::\n\n\n**Cola derecha pesada** — distribución residual lejos de normal. Suma a la subestimación de incertidumbre por heterocedasticidad.\n\n## Plot 3 — Scale-Location {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 3)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08_regresion_multiple_2_files/figure-revealjs/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n\n:::\n\nLínea roja con **pendiente positiva clara** — confirma la heterocedasticidad cuantificada con la métrica anterior.\n\n## Plot 4 — Residuals vs Leverage {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 5)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08_regresion_multiple_2_files/figure-revealjs/unnamed-chunk-6-1.png){width=864}\n:::\n:::\n\n\n:::\n\n::: {.callout-note appearance=\"minimal\"}\nLas curvas punteadas son contornos de **distancia de Cook** (Cook's distance) — métrica clásica de influencia individual. La nombramos hoy (última sesión) para cerrar vocabulario. Distancia de Cook máxima en M3: **0.8687** — bien por debajo del umbral preocupante de 0.5. **Sin alarma.**\n:::\n\n## Veredicto del diagnóstico {.smaller}\n\n| Supuesto | Severidad |\n|---|---|\n| Linealidad | 🟢 Razonable |\n| **Homocedasticidad** | 🔴 **Violación clara (cor = 0.552)** |\n| Independencia | 🟢 Asumida |\n| **Normalidad de residuales** | 🟠 **Cola pesada (asim 2.52, kurt 17.8)** |\n| Influencia individual | 🟢 Sin alarma |\n\n::: {.callout-important}\n**Lectura honesta para Patricia.** Las violaciones son graves. El modelo da **dirección útil** (signos y órdenes de magnitud robustos), pero los **rangos formales son optimistas**. Hay que comunicarlo.\n:::\n\n# Multicolinealidad y VIF {background-color=\"#2C3E50\"}\n\n## El nombre técnico al fenómeno de S7 {.smaller}\n\nEn S7 vimos: agregar `accommodates` al modelo infló el SE de `bedrooms` 2× sin que R² mejorara casi nada. Le dimos un nombre informal: *\"costo del acoplamiento\"*.\n\nEl nombre técnico es **multicolinealidad**: dos o más predictoras contienen información redundante, y el modelo no puede separar bien sus efectos individuales.\n\n::: {.callout-note}\nLa métrica estándar para cuantificarla es el **VIF** (Variance Inflation Factor). Es lo que vamos a calcular ahora.\n:::\n\n## VIF — definición y regla de pulgar {.smaller}\n\nPara cada predictora $X_j$:\n\n$$\\text{VIF}_j = \\frac{1}{1 - R^2_j}$$\n\ndonde $R^2_j$ es el coeficiente de regresar $X_j$ contra **todas las demás predictoras**.\n\n**Lectura.** Si $X_j$ es muy predecible desde las otras → $R^2_j$ alto → $\\text{VIF}_j$ alto → la información de $X_j$ ya estaba en las otras.\n\n| VIF | Lectura |\n|---|---|\n| < 5 | OK |\n| 5 - 10 | Marginal, vigilar |\n| > 10 | Problemático |\n\n## VIF en M3 {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.20em;\"}\n```{.r}\n# VIF para bedrooms\nmod_vif <- lm(bedrooms ~ accommodates + superhost,\n              data = roma)\nvif_bd <- 1 / (1 - summary(mod_vif)$r.squared)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Variable     |  VIF|Lectura  |\n|:------------|----:|:--------|\n|bedrooms     | 5.91|Marginal |\n|accommodates | 5.93|Marginal |\n|superhost    | 1.01|OK       |\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-note}\n**Veredicto:** VIF de bedrooms y accommodates ≈ 5.91 cada uno (simétrico — son intercambiables en su rol). **Borderline pero técnicamente OK.** El \"costo del acoplamiento\" de S7 ahora tiene nombre y métrica — y está dentro de tolerancia.\n:::\n\n# ¿Cuál es nuestro modelo final? {background-color=\"#18BC9C\"}\n\n## Comparación de candidatos {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Modelo              |  k| R² aj| VIF máx|\n|:-------------------|--:|-----:|-------:|\n|M_simple (bedrooms) |  1| 0.550|     1.0|\n|M2 (b + acc)        |  2| 0.573|     5.9|\n|M_alt (b + sh)      |  2| 0.588|     1.0|\n|M3 (b + acc + sh)   |  3| 0.604|     5.9|\n\n\n:::\n:::\n\n\n::: {.incremental}\n- M3 tiene el R² aj más alto, pero apenas 1.6 pp sobre M_alt.\n- M_alt está libre de multicolinealidad (VIF = 1.0).\n- **La decisión no es algorítmica. Es de juicio.**\n:::\n\n## Decisión final: M3 {.smaller}\n\n::: {.callout-note}\n**Mantenemos M3 como modelo final.**\n\nJustificación: la mejora marginal en R² aj (0.604 vs 0.588) **y la capacidad de interpretar el efecto de bedrooms manteniendo la capacidad constante** valen el VIF borderline.\n\n**M_alt sería una alternativa también defendible** para un analista que priorice parsimonia. Ambas son técnicamente válidas. La elección depende del objetivo: aquí queremos interpretación condicional (lo que se sembró desde S6), no solo predicción.\n:::\n\n::: {.callout-warning appearance=\"minimal\"}\n**Para Patricia**: cuando le preguntemos qué historia preferimos contarle del mercado, M3 dice *\"recámaras y capacidad pesan separadamente, ambas matter\"*. M_alt diría *\"recámaras es la palanca observable, capacidad va de pasajera\"*. Eligiendo M3 le damos la versión más rica.\n:::\n\n# Caso integrador {background-color=\"#2C3E50\"}\n\n## Las 3 decisiones encadenadas de [Patricia]{.patricia} {.smaller}\n\n| # | Pregunta | ¿Lo respondemos? |\n|---|---|---|\n| 1 | ¿Listar en Airbnb o renta tradicional? | **No** — fuera de scope (otro dataset) |\n| 2 | Si Airbnb, ¿a qué precio? | **Sí** — predicción central + rango defendible |\n| 3 | ¿Qué ingreso anual proyectar? | **Sí** — con supuesto declarado de ocupación |\n\n## Memo final · Parte A {.smaller}\n\n::: {.callout-note appearance=\"minimal\"}\n**Para: Patricia Domínguez**\n**Asunto: Recomendación final — modelo de precio para su depto en Roma Norte**\n\n**Resumen ejecutivo.** Con base en 980 listings de propiedades completas en Roma Norte, su precio defendible para 2 recámaras / 4 personas está en **\\$0 a \\$4,719 MXN/noche** (predicción central \\$2,225). Si logra superhost: predicción central +\\$137 MXN/noche.\n\n**Decisión 1 — ¿Airbnb o renta tradicional?** No la respondemos con nuestros datos. Resolverla requiere una base de **comparables de renta tradicional** en Roma Norte (precio mensual, ocupación, costos). Esa información no es pública en una sola fuente; habría que construirla con un **web scraper** sobre portales como Inmuebles24, Mercado Libre Inmuebles o Lamudi. Es un proyecto en sí mismo, fuera del alcance de esta consultoría.\n\n**Decisión 2 — ¿A qué precio listar?** Predicción central \\$2,225 MXN/noche; rango defendible (95%, truncado en 0): **\\$0 a \\$4,719**. **Use el rango, no la predicción puntual.** Cada recámara adicional (manteniendo capacidad constante): +\\$862 MXN/noche. Cada persona adicional de capacidad: +\\$269. Superhost: +\\$137.\n:::\n\n## Memo final · Parte B {.smaller}\n\n::: {.callout-note appearance=\"minimal\"}\n**Decisión 3 — ¿Cuál es el ingreso anual esperable?** Asumiendo ocupación de **55%** (201 noches/año reservadas; valor razonable para Roma Norte, a refinar con datos propios después de 3-6 meses): **\\$446,688 MXN/año** sin superhost; **\\$474,285 MXN/año** con superhost. Diferencia atribuible a la certificación: ~\\$27,598 MXN/año.\n\n**Acciones operativas con prioridad.**\n\n1. **Buscar la certificación de superhost** durante el primer año. El premium (~\\$27,598/año) hace que el esfuerzo (responsividad, tasa de aceptación, evitar cancelaciones) tenga retorno claro.\n2. **Considerar capacidad efectiva**, no solo recámaras. Un sofá-cama que aumente accommodates de 4 a 5 captura ~\\$269/noche sin obra física.\n3. **Optimizar señales de calidad** — fotos profesionales, descripción, primeras reseñas. Variables que el modelo no incluye pero que la literatura indica que mueven precios.\n\n**Caveats explícitos.** Heterocedasticidad severa → rangos formales optimistas. Modelo NO establece causalidad. Variables omitidas: m², ubicación específica, calidad del decorado, antigüedad.\n\n**Próximos pasos.** Re-evaluar con datos propios después del primer trimestre. Para profundización: enriquecer con datos georreferenciados (próxima slide).\n:::\n\n# Cierre del Parcial 3 {background-color=\"#18BC9C\"}\n\n## Veredicto del modelo final {.smaller}\n\n::: {.callout-note}\n**M3 es nuestro modelo final.** Es estadísticamente robusto en signos y magnitudes, con multicolinealidad borderline pero técnicamente aceptable. Las violaciones de homocedasticidad y normalidad lo limitan: **da dirección útil pero los rangos formales subestiman incertidumbre real**.\n\n**Para Patricia**: rango defendible \\$0 a \\$4,719 MXN/noche; ingreso anual proyectado \\$446,688 (con ocupación supuesta 55%). Premium superhost: \\$137/noche.\n:::\n\n## Lo que este modelo NO incluye {.smaller}\n\n::: {.callout-important}\n- **Tamaño en m²** — Inside Airbnb no expone esto consistentemente.\n- **Ubicación específica** dentro de Roma Norte (calle, cuadra, esquina). Tratamos a Roma Norte como bloque homogéneo.\n- **Calidad del decorado, fotos, descripción** — variables de presentación que mueven precios.\n- **Reseñas y rating** — historial de calidad.\n- **Variables del entorno** — proximidad a transporte, restaurantes, ruido, seguridad, comercio.\n- **Variables temporales** — estacionalidad, eventos, día de la semana.\n:::\n\n## Cómo mejorar el modelo: enriquecer con datos externos {.smaller}\n\nEl precio de un Airbnb depende de mucho que el dataset no tiene. Cruzar con otras fuentes lo transforma:\n\n::: {.incremental}\n- **Censo INEGI** a nivel manzana / AGEB → ingreso medio del entorno, escolaridad, edad, densidad, marginación\n- **Distancias geográficas** → metro, metrobús, mercados, centros comerciales, parques, puntos turísticos\n- **Tipología vial** (DENUE, OpenStreetMap) → primaria/secundaria, peatonal, ruido esperado\n- **Web scraping** para datos no abiertos: precios de competidores, eventos cercanos\n:::\n\n**Lo que se necesita técnicamente**: geocoding (direcciones a lat/long), joins espaciales con cartografía oficial (`sf`, `tigris`, `osmdata`), web scraping cuando la fuente no es API abierta.\n\n## Pero la geografía agrega supuestos {.smaller}\n\nCuando los datos están en el espacio, OLS necesita más:\n\n| OLS clásico | Versión espacial |\n|---|---|\n| Independencia | **No autocorrelación espacial** — residuos vecinos no deben ser similares (I de Moran) |\n| Linealidad | **Estacionariedad** — el efecto no varía en el espacio |\n| — | **Soporte consistente** — datos del AGEB aplican a todos los listings de ese AGEB |\n\n::: {.callout-warning}\n**Tobler's First Law**: *\"near things are more related than distant things\"*. Listings vecinos comparten ruido, prestigio, comercio. Si lo ignoramos, los SE están subestimados → falsa precisión.\n\n**Modelos formales**: SAR, SEM, GWR. Paquetes: `spdep`, `spatialreg`, `GWmodel`. Más allá del semestre — el camino natural si quieren profundizar.\n:::\n\n## El arco que recorrimos {.smaller}\n\n| Sesión | Pregunta de [Patricia]{.patricia} | Herramienta clave |\n|---|---|---|\n| **S1** | ¿Es real que el promedio es \\$1,800? | t una muestra |\n| **S2** | ¿Cobro más completo o por cuarto? ¿Superhost? | t/z dos muestras + proporciones |\n| **S3** | ¿Roma vs Condesa vs Polanco vs Del Valle? | ANOVA + χ² |\n| **S4** | ¿Cómo paso de comparar a estimar un precio? | `lm` simple |\n| **S5** | ¿Puedo confiar en este modelo? | Diagnóstico + auditoría de datos |\n| **S6** | ¿Cuál es el rango defendible? ¿Es causal? | CI vs PI + omitted variable |\n| **S7** | ¿Y si controlo por varias cosas? | `lm` múltiple + dummies |\n| **S8** | Entrega final defendible | VIF + diagnóstico + memo |\n\n## El principio que cierra el semestre {background-color=\"#2C3E50\" .smaller}\n\n> **\"La pregunta la haces tú.**\n>\n> **La ejecución puede asistirla la IA.**\n>\n> **La verificación y la decisión son intransferibles.\"**\n\n::: {.callout-note appearance=\"minimal\"}\nLo que aprendieron a hacer en este Parcial 3 es exactamente eso: **formular preguntas pertinentes**, **ejecutar los cálculos con criterio**, **verificar honestamente** los resultados y sus límites, y **comunicar a un tomador de decisiones** lo que se puede y no se puede afirmar.\n\nEso es el oficio. Las herramientas cambian. El oficio no.\n:::\n",
    "supporting": [
      "08_regresion_multiple_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}