{
  "hash": "bbc9fb3e9dd84dc48f3b513fab684cda",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"El marco de las pruebas de hipótesis\"\nsubtitle: \"Sesión 1 · Parcial 3 · Análisis de Datos II\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 1 · 2.1 Formulación de hipótesis\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\n    background-transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Contexto del parcial {background-color=\"#2C3E50\"}\n\n## Nueva clienta: [Patricia Domínguez]{.patricia}\n\n:::: {.columns}\n\n::: {.column width=\"55%\" style=\"font-size: 0.90em;\"}\nPatricia acaba de heredar un departamento de 2 recámaras en **Roma Norte**.\n\nQuiere tomar tres decisiones de negocio:\n\n1. ¿Airbnb o renta tradicional?\n2. ¿A qué precio?\n3. ¿Qué ingreso esperar?\n\n:::\n\n::: {.column width=\"45%\"}\n**Ficha de la propiedad**\n\n| | |\n|---|---|\n| Alcaldía | Cuauhtémoc |\n| Colonia | Roma Norte |\n| Tipo | Propiedad completa |\n| Recámaras | 2 |\n| Baños | 1.5 |\n| Capacidad | 4 |\n| Superficie | 62 m² |\n:::\n\nNos ha contratado como su consultora de análisis.\n::::\n\n## La lógica del parcial {.smaller}\n\nCada sesión responde **una nueva pregunta** de Patricia. El análisis se hace más sofisticado semana a semana.\n\n| Sesión | Lo que le entregamos |\n|:---:|:---|\n| **1** | Validación de una afirmación del mercado |\n| 2 | Comparaciones estratégicas |\n| 3 | Análisis entre alcaldías |\n| 4 | Auditoría de un análisis externo |\n| 5–7 | Modelo de precio |\n| 8 | Presentación ejecutiva |\n\n# La pregunta de hoy {background-color=\"#18BC9C\"}\n\n## Patricia llega con un recorte\n\n> *\"Leí en una nota del periódico que un Airbnb promedio en Roma Norte se renta en **$1,800 MXN por noche**. ¿Esa cifra es realista? Si es cierta, quiero basar mis cálculos en ella.\"*\n\n::: {.callout-note}\nEste tipo de afirmación —una cifra publicada en un medio que alguien quiere usar como base de decisión— es **el disparador natural** de una prueba de hipótesis.\n:::\n\n## De pregunta de negocio a pregunta analítica {.smaller}\n\nLa pregunta de Patricia en español:\n\n> \"¿Es creíble que el precio promedio en Roma Norte sea $1,800?\"\n\nLa misma pregunta traducida a estadística:\n\n> \"¿Es razonable que la media poblacional $\\mu$ del precio por noche en Roma Norte sea **igual** a $1,800 MXN, dado lo que observamos en los datos?\"\n\n::: {.callout-warning}\nLa traducción no es trivial. La **primera habilidad profesional** en análisis es saber pasar de una pregunta vaga a una pregunta analizable. La IA no hace esto bien — requiere contexto que solo tú tienes.\n:::\n\n# El marco conceptual {background-color=\"#2C3E50\"}\n\n## ¿Qué es una hipótesis estadística?\n\nUna [hipótesis]{.concepto} es una **afirmación sobre un parámetro poblacional** que se puede evaluar con datos.\n\nFormato:\n\n- La media poblacional **es igual a** un valor.\n- La proporción poblacional **es distinta de** un valor.\n- La media de un grupo **es mayor que** la de otro.\n\nSiempre involucra un parámetro (μ, p, σ) y un valor de referencia.\n\n## Las dos hipótesis {.smaller}\n\nToda prueba contrasta **dos** afirmaciones mutuamente excluyentes:\n\n$H_0$ : [Hipótesis nula]{.concepto}\n: La afirmación que queremos **poner a prueba**. Generalmente representa el *status quo* o la afirmación que otros hacen.\n\n$H_1$ : [Hipótesis alternativa]{.concepto}\n: La afirmación que adoptaríamos si rechazamos $H_0$. Representa lo que sospechamos o queremos demostrar.\n\n<br>\n\n::: {.callout-important}\nNunca \"aceptamos\" $H_0$. La rechazamos o **no logramos rechazarla**. Es una asimetría fundamental de la prueba.\n:::\n\n## Para Patricia\n\nLa afirmación del artículo es la que pondremos a prueba:\n\n$$H_0: \\mu = 1{,}800$$\n$$H_1: \\mu \\neq 1{,}800$$\n\n- Si los datos son consistentes con $H_0$, Patricia puede usar $1,800 como referencia.\n- Si los datos son inconsistentes con $H_0$, la cifra del artículo no es creíble y hay que revisarla.\n\n## Dos tipos de error\n\nEn cualquier decisión bajo incertidumbre, se puede equivocar uno:\n\n| Decisión \\\\ Realidad | $H_0$ verdadera | $H_0$ falsa |\n|:---|:---:|:---:|\n| **Rechazo $H_0$** | Error Tipo I (α) | ✔ Correcto |\n| **No rechazo $H_0$** | ✔ Correcto | Error Tipo II (β) |\n\n## El costo del error, para Patricia {.smaller}\n\nPiensa el costo de negocio de cada error:\n\n- **Tipo I (rechazamos cuando era cierto)** → le decimos a Patricia que $1,800 no es realista, cuando sí lo era. Ella ajusta innecesariamente.\n- **Tipo II (no rechazamos cuando era falso)** → dejamos pasar que la cifra era incorrecta. Patricia basa decisiones en un dato erróneo.\n\n<br>\n\n::: {.callout-note}\nEn negocios, el costo de los dos errores rara vez es simétrico. **Parte del trabajo del analista es explicitar qué error es más grave** en cada caso.\n:::\n\n## Nivel de significancia α {.smaller}\n\nEl [nivel de significancia]{.concepto} $\\alpha$ es la **probabilidad máxima de Error Tipo I** que estamos dispuestos a tolerar.\n\nValores convencionales:\n\n- $\\alpha = 0.05$ · estándar general\n- $\\alpha = 0.01$ · contextos de alto costo de error Tipo I\n- $\\alpha = 0.10$ · exploratorio\n\n::: {.callout-warning}\n0.05 no es mágico. Es una convención razonable para muchos contextos, pero **no es un mandato**. En decisiones de alto impacto, pedir más evidencia (α más bajo) es sensato.\n:::\n\n## El p-valor {.t-70}\n\nEl [p-valor]{.concepto} responde a **una** pregunta muy específica:\n\n> *\"Si $H_0$ fuera verdadera, ¿qué tan raro sería haber observado los datos que observamos?\"*\n\n::: {style=\"font-size: 0.75em;\"}\n**Aterrizado a Patricia.** Supongamos —sólo por el argumento— que la media poblacional en Roma Norte *sí* es \\$1,800 ($H_0$). En nuestra muestra observamos una media de \\$2,111. El p-valor mide **qué tan probable era obtener una muestra así de alejada de \\$1,800, si \\$1,800 fuera la verdad**.\n\n- p-valor **pequeño** → \"sería rarísimo ver \\$2,111 si la verdad fuera \\$1,800\" → **rechazamos $H_0$**.\n- p-valor **grande** → \"\\$2,111 es plausible incluso si la verdad fuera \\$1,800\" → no hay evidencia suficiente.\n\n$$p\\text{-valor} < \\alpha \\implies \\text{rechazamos } H_0$$\n:::\n\n::: {.callout-important}\nEl p-valor **NO es** la probabilidad de que $H_0$ sea cierta. Es la probabilidad de **los datos**, *asumiendo* $H_0$. Confundirlos es el error de interpretación más común.\n:::\n\n# Aplicación al caso Patricia {background-color=\"#18BC9C\"}\n\n## De dónde vienen los datos {.smaller}\n\nTrabajamos con **Inside Airbnb**, un proyecto público que publica snapshots reales de la plataforma bajo licencia CC-BY. Usamos el corte **Ciudad de México · 2025-09-28**.\n\n::: {.panel-tabset style=\"font-size: 1.2em;\"}\n\n## 💻 Código\n\n```{.r}\nlibrary(readr)\nlibrary(dplyr)\n\nurl <- paste0(\n  \"https://data.insideairbnb.com/mexico/df/mexico-city/\",\n  \"2025-09-27/data/listings.csv.gz\")\n\nlistings <- read_csv(url, show_col_types = FALSE)\n\n# `price` viene como texto (\"$1,250.00\"); lo pasamos a numérico.\nlistings <- listings |>\n  mutate(price = parse_number(price)) |>\n  filter(!is.na(price))\n\ndim(listings)\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nDescarga: ~40 MB · se hace una sola vez por sesión.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nListings en el archivo crudo:        27,051\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nListings tras quitar los de price=NA: 23,567  (drop de 3,484)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrimeras columnas disponibles en el dataset:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"id\"                    \"listing_url\"           \"scrape_id\"            \n [4] \"last_scraped\"          \"source\"                \"name\"                 \n [7] \"description\"           \"neighborhood_overview\" \"picture_url\"          \n[10] \"host_id\"               \"host_url\"              \"host_name\"            \n```\n\n\n:::\n:::\n\n\n:::\n\n## Cómo van a replicar esto {.smaller}\n\nLa idea de esta sesión es que cada paso que hagamos aquí **lo tecleen al mismo tiempo en su propio notebook**. Así salen de clase con un análisis reproducible.\n\n1. Abran su notebook (`.ipynb` con kernel de R) **antes** de que avancemos.\n2. Corran el bloque de descarga de la slide anterior. Es la parte más lenta: déjenlo descargando y sigan con los conceptos.\n3. En cada slide con pestaña `💻 Código`, copien el bloque a una celda y ejecútenlo.\n4. En cada resultado, comparen que les da lo mismo que en pantalla.\n\n::: {.callout-important appearance=\"minimal\"}\n**Realismo, no sincronía perfecta.** Si su descarga se atora o se equivocaron en una línea, *no se bloqueen*: avancen con las slides, regresen cuando el objeto esté listo. El entregable al final es tener el resultado de la prueba t y la recomendación a Patricia —no haber ejecutado todo al mismo tiempo que yo.\n:::\n\n## La secuencia de análisis de hoy {.smaller}\n\nAsí se ve el flujo de una consultora real cuando atiende a una clienta como Patricia. Nosotros lo vamos a recorrer completo en esta sesión:\n\n| # | Paso | Qué hacemos | Por qué |\n|:-:|:---|:---|:---|\n| 1 | Obtener datos | `read_csv()` desde Inside Airbnb | Base común, trazable |\n| 2 | Limpiar lo mínimo | `price` → numérico | Sin eso no se calcula nada |\n| 3 | Filtrar el subset | Roma Norte + propiedad completa | Aislar el mercado de Patricia |\n| 4 | Explorar | Descriptivos + histograma | Ver antes de calcular |\n| 5 | Formular $H_0,\\,H_1$ | Traducir la afirmación del artículo | El trabajo analítico real |\n| 6 | Ejecutar prueba | `t.test()` de una muestra | El cálculo en sí |\n| 7 | Interpretar | p-valor + IC en pesos | La decisión |\n| 8 | Comunicar | Memo de 150 palabras | Lo que Patricia se lleva |\n\n## Los datos de Roma Norte {.smaller}\n\nAntes de la prueba, siempre exploramos los datos. ¿Qué vemos?\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.20em;\"}\n```{.r}\nroma_norte <- listings |>\n  filter(host_neighbourhood == \"Roma Norte\",\n         room_type == \"Entire home/apt\")\n\nroma_norte |>\n  summarise(\n    n           = n(),\n    media       = mean(price),\n    mediana     = median(price),\n    desv_est    = sd(price),\n    minimo      = min(price),\n    maximo      = max(price)\n  )\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|   n| Media| Mediana| Desv. est.| Mínimo| Máximo|\n|---:|-----:|-------:|----------:|------:|------:|\n| 983| 2,111|   1,493|      3,193|    436| 81,000|\n\n\n:::\n:::\n\n\n:::\n\n## Distribución del precio en Roma Norte {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nggplot(roma_norte, aes(x = price)) +\n  geom_histogram(bins = 40, fill = \"#18BC9C\",\n                 color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = 1800, color = \"#E74C3C\",\n             linewidth = 1, linetype = \"dashed\") +\n  geom_vline(xintercept = mean(roma_norte$price),\n             color = \"#2C3E50\", linewidth = 1) +\n  annotate(\"text\", x = 1800, y = Inf, label = \"Afirmación: $1,800\",\n           color = \"#E74C3C\", hjust = -0.1, vjust = 2) +\n  scale_x_continuous(labels = label_comma()) +\n  labs(\n    title = \"Precio por noche en Roma Norte (propiedad completa)\",\n    subtitle = \"Línea roja: afirmación del artículo | Línea oscura: media observada\",\n    x = \"Precio (MXN por noche)\",\n    y = \"Número de listings\"\n  )\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01_marco_pruebas_hipotesis_files/figure-revealjs/unnamed-chunk-3-1.png){width=864}\n:::\n:::\n\n\n:::\n\n## Ejecutamos la prueba {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\n# Prueba t de una muestra, bilateral (≠)\nt.test(\n  x           = roma_norte$price,\n  mu          = 1800,\n  alternative = \"two.sided\",\n  conf.level  = 0.95\n)\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  roma_norte$price\nt = 3.0506, df = 982, p-value = 0.002345\nalternative hypothesis: true mean is not equal to 1800\n95 percent confidence interval:\n 1910.825 2310.532\nsample estimates:\nmean of x \n 2110.679 \n```\n\n\n:::\n:::\n\n\n:::\n\n## Lectura profesional del output\n\nTres cosas que debes **siempre** reportar, en este orden:\n\n1. **Estadístico y p-valor**: ¿rechazamos $H_0$? ¿Con qué fuerza?\n2. **Intervalo de confianza**: ¿dentro de qué rango está la media real con 95% de confianza?\n3. **Interpretación en pesos y contexto**: ¿qué significa esto para Patricia?\n\nNo reportes solo \"p < 0.05\". Eso no es un análisis, es un trámite.\n\n## ¿Qué le decimos a Patricia? {.smaller}\n\nUna versión profesional de la comunicación:\n\n::: {.callout-note}\n**Recomendación preliminar.** Con base en 983 propiedades completas listadas en Roma Norte al corte de septiembre de 2025, el precio promedio observado es de \\$2,111 MXN por noche, con intervalo de confianza al 95% entre \\$1,911 y \\$2,311. La cifra de \\$1,800 mencionada en el artículo está **fuera** de ese intervalo (p = 0.00235), por lo que no recomendamos usarla como referencia. La mediana observada de \\$1,493 puede ser una referencia más robusta dada la asimetría típica del mercado.\n:::\n\n## Lo que esta prueba NO le dice a Patricia {.smaller}\n\n::: {.callout-important}\nLa prueba confirma que \\$1,800 **no es la media** del mercado. Pero **NO nos dice:**\n\n- Qué precio cobrar en su propiedad específica\n- Si su ubicación dentro de Roma Norte es mejor o peor que el promedio\n- Cómo fluctúa el precio por temporada\n- Cómo se compara con otras alcaldías\n\nCada una de esas preguntas requiere un análisis distinto. Las iremos trabajando en las próximas sesiones.\n:::\n\n# Actividad para notebook {background-color=\"#2C3E50\"}\n\n## Lo que harán en su notebook {.t-60}\n\nRepliquen este análisis en su propio `.ipynb`:\n\n1. Cargar `listings_cdmx.rds`\n2. Filtrar Roma Norte, propiedad completa\n3. Reproducir el histograma\n4. Ejecutar la prueba t de una muestra contra \\$1,800\n5. Redactar en celda de markdown (max. 150 palabras) **la recomendación a Patricia** con el formato: qué encontramos, qué tan confiables somos, qué NO sabemos, qué recomendamos.\n\nEsta redacción cuenta para la participación del parcial.\n\n## Para la próxima sesión\n\nPatricia regresa con más preguntas:\n\n> *\"Veo que $1,800 no era realista. Ahora: ¿cobro más rentando el depto entero o mejor un cuarto? ¿Los superhosts realmente cobran más? ¿Vale la pena diferenciar el precio entre semana y fin de semana?\"*\n\nTres comparaciones, tres pruebas distintas. **Sesión 2: pruebas de dos muestras.**\n\n# Recapitulación {background-color=\"#18BC9C\"}\n\n## Llevaron hoy {.smaller}\n\n1. El [marco conceptual]{.concepto} de prueba de hipótesis: $H_0$, $H_1$, errores tipo I y II, $\\alpha$, p-valor.\n2. Cómo traducir una pregunta de negocio a una prueba estadística.\n3. Cómo ejecutar una prueba t de una muestra en R.\n4. Cómo interpretar y comunicar responsablemente el resultado.\n5. Qué puede y qué **no** puede responder esta prueba.\n\n---\n\n**¿Preguntas?**\n",
    "supporting": [
      "01_marco_pruebas_hipotesis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}