{
  "hash": "604f0bfeb75b5da647216ad591a16c29",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión simple II: validez, supuestos y diagnóstico\"\nsubtitle: \"Sesión 5 · Parcial 3 · Análisis de Datos II\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 5 · 5.2 Validez · 5.3 Pendiente · 5.4 RSE y R²\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Recapitulación {background-color=\"#2C3E50\"}\n\n## Lo que llevamos con [Patricia]{.patricia} {.smaller}\n\n**Sesión 4** — Construimos un modelo de regresión simple:\n\n$$\\widehat{\\text{precio}} = -81 + 1,281 \\times \\text{recámaras}$$\n\nPara su depto de 2 recámaras, el modelo predijo **\\$2,481 MXN/noche**.\n\nPatricia tiene un número. Pero un número sin auditoría no es una decisión.\n\n## La pregunta más madura de [Patricia]{.patricia} {.smaller}\n\n> *\"Me dieron un modelo y un número. Pero antes de basar mi decisión financiera en eso, necesito saber: ¿qué tan **confiable** es? ¿Cómo sé que el modelo no está **mal**? ¿Hay algo en los datos que lo **invalide**?\"*\n\n::: {.callout-note}\nPatricia ya no quiere solo respuestas. Quiere saber **cuánto confiar en ellas**. Es la pregunta que distingue a un tomador de decisiones serio: pedir auditoría antes de comprometer recursos.\n:::\n\n## ¿Qué significa \"auditar un modelo\"? {.smaller}\n\nCuatro preguntas separadas:\n\n0. **¿Los datos sobre los que se construyó son confiables?** — *auditoría de datos*\n1. **¿El modelo es internamente coherente?** ¿Cumple los supuestos? — *diagnóstico*\n2. **¿La relación es estadísticamente robusta?** ¿O podría ser puro azar? — *prueba de la pendiente*\n3. **¿Qué tan bien explica los datos reales?** ¿Buen ajuste o solo dirección? — *R² y RSE*\n\n::: {.callout-warning appearance=\"minimal\"}\nLa pregunta **0** se salta con frecuencia. Pero un modelo construido sobre datos sucios produce diagnósticos engañosos. **Empecemos por ahí.**\n:::\n\n# Antes de auditar el modelo {background-color=\"#E74C3C\"}\n\n## Un atípico que arrastramos {.smaller}\n\nDesde S1 vimos en los gráficos un punto **muy** despegado del resto. Lo señalamos pero no lo gestionamos. Hoy sí.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05_regresion_simple_2_files/figure-revealjs/unnamed-chunk-1-1.png){width=864}\n:::\n:::\n\n\n## El listing en cuestión {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\nroma_full |>\n  arrange(desc(price)) |>\n  select(id, price, bedrooms,\n         accommodates, property_type) |>\n  head(5)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|           id|  price| bedrooms| accommodates|property_type      |\n|------------:|------:|--------:|------------:|:------------------|\n| 3.969345e+07| 81,000|        1|            2|Entire rental unit |\n| 4.934523e+07| 21,554|        7|           14|Tiny home          |\n| 7.419507e+17| 18,042|        7|           16|Entire condo       |\n| 7.350638e+17| 17,624|        9|           16|Entire condo       |\n| 9.209329e+17| 16,267|        7|           16|Entire rental unit |\n\n\n:::\n:::\n\n\n:::\n\nEl máximo (\\$81,000) está en una propiedad de **1 recámara para 2 personas**. El segundo (\\$21,554) es una propiedad de **7 recámaras para 14 personas** — sí justifica su tarifa. El atípico **no es lujo real**; es casi seguro un error de captura del host.\n\n## El criterio: dominio, no estadística mecánica {.smaller}\n\n::: {.incremental}\n- El listing problemático tiene `bedrooms = 1` — la categoría **más común** del subset, no una zona inusual.\n- Su efecto sobre los **coeficientes** del modelo (β₀, β₁) es **modesto** — no mueve la pendiente.\n- Pero su residuo gigante (≈ \\$80,000) **al cuadrado** **distorsiona el RSE y el R²**.\n:::\n\n::: {.callout-warning}\n**Lección antes de empezar:** un humano que conoce el mercado de Airbnb en CDMX **sabe** que \\$81,000/noche para 1 recámara/2 personas no es lujo real, es un error de captura. **El criterio correcto aquí es de dominio**, no estadístico.\n:::\n\n## Decisión: cap por dominio en P99.9 {.smaller}\n\n**Regla de filtrado:** descartamos listings con `price > P99.9` (≈ \\$22,743).\n\n```{.r}\np99_9 <- quantile(roma_full$price, 0.999)\nroma  <- roma_full |> filter(price <= p99_9)\n```\n\n- Cae **1 listing** (el de \\$81,000).\n- Las propiedades grupales legítimas de 7+ recámaras (\\$15k-\\$21k) **siguen en el dataset**.\n- Documentado, reproducible, justificable: *\"para Airbnb residencial en Roma Norte, precios > P99.9 son implausibles para el mercado real.\"*\n\n## Modelo original vs modelo depurado {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Métrica                     | Con atípico| Sin atípico|\n|:---------------------------|-----------:|-----------:|\n|n                           |         981|         980|\n|β₀ intercepto (MXN)         |         -81|        -245|\n|β₁ pendiente (MXN/recámara) |       1,281|       1,329|\n|R²                          |       0.193|       0.551|\n|RSE (MXN)                   |       2,872|       1,318|\n|Predicción 2 rec. (MXN)     |       2,481|       2,413|\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"minimal\"}\n**Coeficientes apenas cambian** — el atípico estaba en `bedrooms = 1`, low leverage. **R² mejora y RSE baja sustancialmente**: el residuo gigante inflaba la SS_res. La dirección y magnitud del efecto que reportamos en S4 sigue siendo correcta; lo que mejora es la **confianza en la predicción puntual**.\n:::\n\n**De aquí en adelante**, todo el diagnóstico se hace sobre el modelo depurado.\n\n# Los 4 supuestos {background-color=\"#18BC9C\"}\n\n## El modelo lineal hace 4 promesas {.smaller}\n\n| # | Supuesto | Intuición | Cómo lo diagnosticamos |\n|---|---|---|---|\n| 1 | **Linealidad** | La relación X→Y es aproximadamente recta | Residuals vs Fitted |\n| 2 | **Homocedasticidad** | La dispersión es la misma a lo largo de X | Scale-Location |\n| 3 | **Independencia** | Las observaciones no se afectan entre sí | Diseño del muestreo |\n| 4 | **Normalidad de residuales** | Los errores se distribuyen normalmente | Q-Q plot |\n\n::: {.callout-warning appearance=\"minimal\"}\n**Si alguna promesa se rompe**, las conclusiones del modelo pueden ser desde *imprecisas* (sesgo en los errores estándar) hasta *basura* (estimaciones engañosas). Pero ninguna se cumple perfectamente: el juicio está en saber qué tan grave es la violación.\n:::\n\n# Diagnóstico visual {background-color=\"#2C3E50\"}\n\n## Antes de leer los plots: una advertencia {.smaller}\n\n`bedrooms` es **discreta** (0, 1, 2, 3, …), no continua. Esto distorsiona la apariencia de los plots:\n\n::: {.incremental}\n- En residuals-vs-fitted: los puntos forman **bandas verticales** (hay sólo unos pocos valores ajustados distintos).\n- En leverage: todos los puntos con el mismo `bedrooms` tienen leverage idéntico → **columnas verticales**.\n- La curva LOWESS roja por defecto **pierde mucho de su utilidad**.\n:::\n\n::: {.callout-tip}\n**Lo que sí funciona normal:** el Q-Q plot (no depende de X). Y la **altura** de cada banda en los demás plots — eso sí informa sobre homocedasticidad.\n:::\n\n## Plot 1 — Residuals vs Fitted {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 1)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05_regresion_simple_2_files/figure-revealjs/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n\n:::\n\n**Qué buscamos.** Línea roja plana sobre cero (linealidad) y bandas de altura similar (homocedasticidad).\n\n**Qué encontramos.** Las bandas verticales son artefacto de `bedrooms` discreta. **La banda crece con el número de recámaras → heterocedasticidad clara.**\n\n## Plot 2 — Q-Q de residuales {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 2)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05_regresion_simple_2_files/figure-revealjs/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n\n:::\n\n**Qué buscamos.** Los puntos siguen la diagonal → residuales normales.\n\n**Qué encontramos.** La cola izquierda se ajusta razonablemente. La **cola derecha se despega fuerte**: los listings caros (Roma tiene casas de lujo) producen residuales mucho más grandes que los esperados bajo normalidad.\n\n## Plot 3 — Scale-Location {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 3)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05_regresion_simple_2_files/figure-revealjs/unnamed-chunk-6-1.png){width=864}\n:::\n:::\n\n\n:::\n\n**Qué buscamos.** Línea roja plana → varianza constante.\n\n**Qué encontramos.** Línea roja con **pendiente positiva clara**. Confirma la heterocedasticidad detectada en el plot 1: la varianza crece sistemáticamente con el valor ajustado.\n\n## Plot 4 — Residuals vs Leverage {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nplot(modelo, which = 5)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05_regresion_simple_2_files/figure-revealjs/unnamed-chunk-7-1.png){width=864}\n:::\n:::\n\n\n:::\n\n**Qué buscamos.** Que ningún punto se aleje mucho **a la vez** en residuo (vertical) y leverage (horizontal). Las curvas punteadas del plot son referencias de \"puntos influyentes\": si un punto cayera fuera, estaría moviendo el modelo de forma desproporcionada.\n\n**Qué encontramos.** Los listings con muchas recámaras tienen leverage alto por construcción (son raros). Pero **ninguno cae fuera de las referencias** — el modelo no está siendo movido por un punto único.\n\n## Diagnóstico complementario {.smaller}\n\nComo el LOWESS se distorsiona con X discreta, miramos directamente la dispersión por nivel de recámaras.\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.20em;\"}\n```{.r}\nroma_aug <- roma |>\n  mutate(residuo = residuals(modelo))\n\nggplot(roma_aug, aes(x = factor(bedrooms),\n                     y = residuo)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_boxplot()\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05_regresion_simple_2_files/figure-revealjs/unnamed-chunk-8-1.png){width=864}\n:::\n:::\n\n\n:::\n\n## Veredicto del diagnóstico visual {.smaller}\n\n| Supuesto | Severidad de la violación |\n|---|---|\n| Linealidad | 🟢 Razonable |\n| Homocedasticidad | 🟠 Violación clara — varianza crece con # recámaras |\n| Independencia | 🟢 Asumida (cada listing es un anuncio distinto) |\n| Normalidad de residuales | 🟡 Cola derecha pesada (luxury listings) |\n\n::: {.callout-note appearance=\"minimal\"}\n**Lectura.** Las violaciones no son catastróficas: la dirección del efecto es robusta. Pero sí debilitan la **precisión** de cualquier predicción puntual — los errores estándar reportados subestiman la incertidumbre real, especialmente en propiedades grandes.\n:::\n\n# La pendiente {background-color=\"#18BC9C\"}\n\n## ¿β₁ es distinta de cero? {.smaller}\n\nSi la pendiente fuera **cero**, las recámaras no tendrían relación con el precio: agregar o quitar una no cambiaría la estimación. El modelo sería inútil.\n\n::: {.callout-important appearance=\"minimal\"}\nLo que probamos:\n\n- **H₀:** β₁ = 0 (las recámaras no afectan el precio)\n- **H₁:** β₁ ≠ 0 (sí lo afectan)\n:::\n\n**Esto no es un concepto nuevo.** Es exactamente la misma estructura de la prueba *t* de S1 y de las comparaciones de S2 — sólo cambia el parámetro que evaluamos.\n\n## El reframe: misma lógica que S1-S2 {.smaller}\n\n| Concepto | S1 (t una muestra) | S5 (pendiente) |\n|---|---|---|\n| H₀ | μ = μ₀ | β₁ = 0 |\n| H₁ | μ ≠ μ₀ | β₁ ≠ 0 |\n| Estadístico | $t = \\dfrac{\\bar{x} - \\mu_0}{SE}$ | $t = \\dfrac{\\hat\\beta_1}{SE(\\hat\\beta_1)}$ |\n| Decisión | rechazar si p < α | rechazar si p < α |\n\n`lm()` ya hace este test por nosotros. Solo hay que **leer el output**.\n\n## Lectura del `summary(modelo)` {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nsummary(modelo)$coefficients\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|            |  Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-----------|---------:|----------:|-------:|------------------:|\n|(Intercept) | -245.3282|    78.0582| -3.1429|             0.0017|\n|bedrooms    | 1329.2894|    38.3881| 34.6276|             0.0000|\n\n\n:::\n:::\n\n\n:::\n\nFila `bedrooms`:\n\n- **Estimate** = 1,329 (la pendiente estimada)\n- **Std. Error** = 38 (su precisión)\n- **t value** = 34.63 (cuántos errores estándar de cero)\n- **Pr(>|t|)** = <1e-16 (la probabilidad bajo H₀)\n\n## La conclusión {.smaller}\n\nCon un p-valor de <1e-16, **rechazamos H₀ con holgura**.\n\n**Interpretación honesta para Patricia:**\n\n> *La asociación entre recámaras y precio no es producto del azar. Si el efecto fuera realmente cero, sería prácticamente imposible observar lo que vimos en estos 980 listings.*\n\n::: {.callout-warning appearance=\"minimal\"}\n\"Estadísticamente significativo\" **no** significa \"grande\", \"útil\", ni \"causal\". Significa: *\"no es razonable atribuirlo al azar\"*. La distinción entre significancia estadística y relevancia práctica la cerramos en la próxima sección con R² y RSE.\n:::\n\n## Intervalo de confianza para β₁ {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nconfint(modelo, \"bedrooms\", level = 0.95)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            2.5 %   97.5 %\nbedrooms 1253.957 1404.622\n```\n\n\n:::\n:::\n\n\n:::\n\n**IC 95% para la pendiente**: [\\$1,254 , \\$1,405].\n\nLectura: *\"Con 95% de confianza, cada recámara adicional se asocia con un aumento de entre \\$1,254 y \\$1,405 por noche.\"* El cero está claramente fuera del intervalo → consistente con rechazar H₀.\n\n# Bondad de ajuste {background-color=\"#2C3E50\"}\n\n## ¿Cuánto explica el modelo? {.smaller}\n\nSaber que la pendiente no es cero **no es suficiente**. También necesitamos saber:\n\n- ¿Qué tan **bien** ajusta el modelo a los datos? — eso es **R²**\n- ¿Qué tan **grande** es el error típico de predicción? — eso es **RSE**\n\nSon preguntas distintas: *significativo* y *útil* no son lo mismo.\n\n## R² — la proporción explicada {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nsummary(modelo)$r.squared\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nR² = 0.551\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² ajustada = 0.550\n```\n\n\n:::\n:::\n\n\n:::\n\n**R² = 0.551**. El número de recámaras explica **55% de la variabilidad** en precios.\n\nEl **45% restante** depende de variables que el modelo no incluye: tamaño exacto, amenidades, ubicación específica dentro de Roma Norte, calidad de fotos, reseñas, capacidad…\n\n## RSE — el error típico en pesos {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nsummary(modelo)$sigma\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRSE = 1318 MXN\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRSE / media = 64.9%\n```\n\n\n:::\n:::\n\n\n:::\n\n**RSE ≈ \\$1,318 MXN/noche**. Es el error típico de predicción del modelo.\n\nComparado con la media del mercado (\\$2,031), representa **~65% de ruido relativo**. Si el modelo dice \\$2,500, un precio razonable real podría estar entre ~\\$1,500 y ~\\$3,500.\n\n## ¿R² bajo = modelo inútil? {.smaller}\n\n**No necesariamente.** Hay tres lecturas posibles:\n\n::: {.incremental}\n1. **Dirección sí, precisión no.** El modelo nos dice con alta certeza que más recámaras → más precio. Útil para discusión cualitativa.\n2. **Insuficiente para decisión financiera.** Un RSE de 65% del precio promedio es demasiado para fijar un precio único.\n3. **El R² bajo es un mensaje, no un fracaso.** Está diciendo: *\"hace falta más información\"*. Eso es exactamente lo que arreglaremos con regresión múltiple en S7.\n:::\n\n::: {.callout-tip appearance=\"minimal\"}\nUn modelo con R² bajo puede ser **honesto y útil** si comunicamos que entrega orientación, no precisión. El error es presentar una predicción puntual como si fuera un dato firme.\n:::\n\n# Cierre {background-color=\"#18BC9C\"}\n\n## Veredicto para [Patricia]{.patricia} {.smaller}\n\n::: {.callout-note appearance=\"minimal\"}\n**Auditoría de datos.** Detectamos un listing con \\$81,000/noche en una propiedad de 1 recámara — error de captura casi seguro. Lo descartamos. La predicción depurada para 2 recámaras es **\\$2,413** (vs. \\$2,481 de S4).\n\n**Lo bueno del modelo.** La asociación recámaras → precio es **estadísticamente robusta** (p < 0.001). Cada recámara adicional se asocia con un aumento de entre \\$1,254 y \\$1,405 por noche (IC 95%).\n\n**Lo preocupante.** El modelo solo explica **~55%** de la variabilidad en precios, con un error típico de **\\$1,318 MXN/noche**. Heterocedasticidad clara y cola derecha pesada **no invalidan la dirección** del efecto, pero **debilitan la precisión** de cualquier predicción puntual.\n\n**Conclusión.** La estimación de \\$2,413 es **un rango orientativo**, no un precio para fijar. Necesitamos más variables antes de comprometer la decisión financiera de Patricia.\n:::\n\n## Lo que este diagnóstico NO le dice a [Patricia]{.patricia} {.smaller}\n\n::: {.callout-important}\n- **Cumplir supuestos no implica que el modelo sea útil.** Un modelo puede pasar todos los diagnósticos y seguir siendo poco informativo.\n- **El diagnóstico es interno al modelo.** No compara este modelo con uno mejor; sólo evalúa si éste es internamente coherente.\n- **No detecta variables omitidas.** Si la \"verdadera\" variable que mueve el precio es metros cuadrados (que correlaciona con recámaras), nuestro diagnóstico no lo identifica.\n- **No habla de causalidad.** Cumplir los 4 supuestos no convierte una asociación en una causa.\n- **El IC95 de la pendiente no es el IC95 de una predicción.** Un depto específico tiene un rango de precio mucho más amplio. *Eso es la próxima sesión.*\n:::\n\n# Actividad para notebook {background-color=\"#2C3E50\"}\n\n## Lo que harán en su notebook {.smaller}\n\nRepliquen la auditoría del modelo `precio ~ recámaras`:\n\n1. **Auditoría de datos.** Identifiquen el listing extremo del subset y registren su decisión: ¿filtran por P99.9, por dominio, o algo distinto? Justifiquen por escrito.\n2. Refit del modelo sobre el dataset depurado.\n3. Generar los 4 plots de `plot(modelo)`. Para cada uno: una oración sobre qué encontraron.\n4. Calcular: R², R² ajustada, RSE, IC 95% de β₁.\n5. Comparar coeficientes y RSE **con vs sin** el atípico (tabla de 2 columnas).\n6. Redactar un **párrafo profesional** (máx. 200 palabras) para Patricia que responda explícitamente:\n   - ¿Por qué descartaron el atípico?\n   - ¿El modelo es **estadísticamente** robusto?\n   - ¿Es **prácticamente** preciso?\n   - ¿Qué le recomiendan **hacer** con esta auditoría?\n\n# Próxima sesión {background-color=\"#18BC9C\"}\n\n## Lo que llevan hoy {.smaller}\n\n1. **Auditar un modelo empieza por auditar los datos.** Un atípico extremo puede invalidar diagnósticos sin que indicadores estadísticos automáticos lo marquen — el criterio es de **dominio**, no estadístico.\n2. Los **4 supuestos** del modelo lineal y cómo diagnosticarlos visualmente con `plot(modelo)`.\n3. **`bedrooms` discreta** distorsiona los plots — hay que leerlos en contexto.\n4. La **prueba de la pendiente** es la misma estructura que las pruebas de S1-S2: H₀: β₁ = 0.\n5. **Significativo ≠ útil.** R² y RSE responden la pregunta práctica.\n6. Cuando el R² es bajo, el modelo **no es un fracaso** — es una invitación a incluir más variables.\n\n## Para [Patricia]{.patricia}, lo que sigue {.smaller}\n\nTenemos un modelo auditado. Sabemos qué tan confiable es. Pero todavía falta:\n\n- **Convertir la predicción puntual en un rango**: ¿con qué incertidumbre debe planear sus ingresos?\n- **Distinguir IC de la media vs IC de una predicción**: cosas distintas, errores distintos.\n- **Hablar de causalidad sin hacer trampa**: ¿agregar una recámara *causa* un aumento de precio?\n\n**Sesión 6: Regresión simple III — interpretación, predicción y causalidad.**\n",
    "supporting": [
      "05_regresion_simple_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}