{
  "hash": "1f78905b7bc724ff3a0a2805399a340f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión simple III: interpretación, predicción y causalidad\"\nsubtitle: \"Sesión 6 · Parcial 3 · Análisis de Datos II\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 6 · 5.5 Interpretación · 5.6 Predicción · Causalidad\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Recapitulación + relectura {background-color=\"#2C3E50\"}\n\n## Lo que llevamos con [Patricia]{.patricia} {.smaller}\n\n**Sesión 4** — Construimos un modelo: $\\widehat{\\text{precio}} = \\beta_0 + \\beta_1 \\times \\text{recámaras}$.\n\n**Sesión 5** — Lo auditamos. Detectamos un atípico de captura, lo depuramos. Verificamos los 4 supuestos. Probamos que la pendiente es estadísticamente robusta. Discutimos R² y RSE.\n\n**Hoy** — Patricia trae la pregunta operativa final del bloque:\n\n> *\"Dame el número y su margen de error. Y explícame si lo que veo se puede leer como **causa** o solo como **asociación**.\"*\n\n## ¿Qué nos falta para responderle? {.smaller}\n\nTenemos un punto: **2,413 MXN/noche** para 2 recámaras. Pero un punto sin rango no es una respuesta operativa.\n\n::: {.incremental}\n1. **Rango defendible.** ¿Cuánto puede variar el precio de un depto particular como el de Patricia?\n2. **Lectura causal honesta.** ¿Es que más recámaras *causa* mayor precio? ¿O es asociación?\n:::\n\nHoy resolvemos las dos.\n\n## Releyendo β₀ y β₁ con todo el contexto {.smaller}\n\nDespués de S4 y S5, los coeficientes ya no son técnicos abstractos — son afirmaciones específicas que sabemos cómo defender.\n\n$$\\widehat{\\text{precio}} = -245 + 1,329 \\times \\text{recámaras}$$\n\n::: {.callout-note}\n**β₁ = 1,329 MXN/recámara** dice exactamente esto:\n\n*Comparando deptos en Roma Norte que difieren en una recámara, los precios estimados difieren en promedio en \\$1,329 MXN/noche, con un margen de confianza del 95% entre \\$1,254 y \\$1,405.*\n:::\n\n**No** dice que agregar una recámara cause ese aumento. Esa es la conversación de la sección sobre causalidad.\n\n## β₀ en su lugar {.smaller}\n\n$$\\beta_0 = -245 \\text{ MXN}$$\n\n`bedrooms = 0` corresponde a **estudios**. En el subset depurado hay 36 estudios. Si el intercepto es negativo, **no significa que un estudio cuesta menos que cero**: es el valor matemático que mejor posiciona la recta dada la nube de datos completa.\n\n::: {.callout-warning appearance=\"minimal\"}\nLa interpretación útil del modelo empieza en `bedrooms ≥ 1`. β₀ es un parámetro técnico, no una predicción de mercado.\n:::\n\n# De un punto a un rango {background-color=\"#18BC9C\"}\n\n## El salto conceptual {.smaller}\n\nPatricia tiene un punto: **\\$2,413 MXN/noche**. Para una decisión financiera necesita un rango.\n\n`predict()` puede entregar **dos rangos diferentes** — y confundirlos es el error más común en comunicación de resultados.\n\n| Rango | Pregunta que responde | A quién le importa |\n|---|---|---|\n| **IC para E[Y\\|X]** | ¿En qué rango está el **promedio** del mercado de deptos como el suyo? | Análisis de mercado |\n| **IC de predicción Y\\|X** | ¿En qué rango caerá probablemente **SU** depto en particular? | Decisión operativa de Patricia |\n\n## IC para la media: E[Y \\| X = 2] {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\npredict(modelo,\n        newdata  = data.frame(bedrooms = 2),\n        interval = \"confidence\",\n        level    = 0.95)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 2413 2328 2499\n```\n\n\n:::\n:::\n\n\n:::\n\n**Lectura.** *\"Si pudiéramos repetir el muestreo de Roma Norte muchas veces, en el 95% de las muestras el precio promedio condicional para deptos de 2 recámaras estaría entre \\$2,328 y \\$2,499.\"*\n\nHabla del **promedio** de muchos deptos, no de un depto en particular.\n\n## IC de predicción: Y \\| X = 2 nueva {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\npredict(modelo,\n        newdata  = data.frame(bedrooms = 2),\n        interval = \"prediction\",\n        level    = 0.95)\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 2413 -175 5001\n```\n\n\n:::\n:::\n\n\n:::\n\n**Lectura.** *\"Si listamos un depto nuevo de 2 recámaras (como el de Patricia), en el 95% de los casos su precio caerá entre \\$-175 y \\$5,001.\"*\n\nCubre la variabilidad **entre deptos individuales**. Es el rango que importa para Patricia.\n\n## El contraste numérico {.smaller}\n\n| Tipo de rango | Bordes | Ancho |\n|---|---|---|\n| IC para la media E[Y\\|X=2] | [\\$2,328 , \\$2,499] | \\$171 |\n| IC de predicción Y\\|X=2 | [\\$-175 , \\$5,001] | \\$5,176 |\n| **Razón de anchos** | | **30×** |\n\n::: {.callout-important}\nEl rango de predicción es **30 veces más ancho** que el de la media. Reportarle a Patricia el rango angosto cuando lo que necesita es el ancho sería un error grave de comunicación.\n:::\n\n## Visualización contrastante {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_regresion_simple_3_files/figure-revealjs/unnamed-chunk-3-1.png){width=1056}\n:::\n:::\n\n\nLa nube verde es la realidad del mercado. La banda roja **encuadra** esa nube; la azul angosta solo refleja precisión sobre el promedio.\n\n## Aplicación al depto de [Patricia]{.patricia} — versión cruda {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Tipo                               |Valor               |\n|:----------------------------------|:-------------------|\n|Predicción puntual                 |2,413 MXN           |\n|IC 95% para la media E[Y&#124;X=2] |[2,328 , 2,499] MXN |\n|IC 95% de predicción Y&#124;X=2    |[-175 , 5,001] MXN  |\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n**Lectura honesta del PI inferior.** El extremo inferior del intervalo de predicción puede caer en valores negativos (\\$-175 aquí). No es un error de cálculo: el modelo lineal asume errores normales **simétricos** y los precios reales tienen asimetría. Para comunicación ejecutiva, **truncamos en 0** y lo declaramos.\n:::\n\n## Para Patricia — versión ejecutiva {.smaller}\n\n::: {.callout-note appearance=\"minimal\"}\n**Para su depto de 2 recámaras en Roma Norte:**\n\n- **Predicción central**: \\$2,413 MXN/noche\n- **Rango defendible (IC 95% de predicción, truncado en 0)**: \\$0 a \\$5,001 MXN/noche\n\nEse rango ancho refleja la heterogeneidad del mercado de Roma Norte que el modelo simple no captura: tamaño exacto, ubicación específica, amenidades, calidad del host. **Es lo más estrecho que podemos defender hoy.** Lo trabajaremos con más variables en la próxima sesión.\n:::\n\n## Extrapolación: ¿qué pasa con 8 recámaras? {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Recámaras |   n|\n|:---------|---:|\n|0         |  36|\n|1         | 457|\n|2         | 343|\n|3         |  96|\n|4         |  22|\n|5         |  10|\n|6         |   7|\n|7         |   7|\n|9         |   2|\n\n\n:::\n:::\n\n\nPara `bedrooms = 8` el modelo entrega:\n\n- Predicción puntual: \\$10,389 MXN/noche\n- IC de predicción: [\\$7,758 , \\$13,020]\n- **Listings con exactamente 8 recámaras: 0**\n\n::: {.callout-important}\nLa aritmética del intervalo no avisa cuando no hay datos. Para `bedrooms = 8` no hay listings que validen la predicción. **Cuanto más lejos del centro de los datos, menos defendible es la predicción**, sin importar qué tan estrecho sea el intervalo numérico.\n:::\n\n# Causalidad vs correlación {background-color=\"#2C3E50\"}\n\n## ¿La pendiente es causal? {.smaller}\n\n> Cada recámara adicional **se asocia** con +\\$1,329 MXN/noche.\n\n¿Podemos cambiar **se asocia** por **causa**? Eso requeriría afirmar:\n\n> *Si tomáramos el mismo depto y le agregáramos una recámara, su precio justo subiría en \\$1,329 MXN/noche.*\n\nEsto necesita **intervención** (real o hipotética), no observación.\n\n::: {.callout-warning appearance=\"minimal\"}\n**Sesgo por variable omitida.** Si una tercera variable está correlacionada con `bedrooms` Y afecta `price`, parte de lo que atribuimos a `bedrooms` en realidad pertenece a esa tercera variable.\n:::\n\n## Variable confusora candidata: `accommodates` {.smaller}\n\n`accommodates` (capacidad declarada en Airbnb) es un confusor natural: depende de las recámaras *y* afecta el precio.\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.30em;\"}\n```{.r}\ncor(roma$bedrooms, roma$accommodates)\nlm(price ~ accommodates, data = roma) |> summary()\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\ncor(bedrooms, accommodates) = 0.88\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlm(price ~ accommodates):\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  β₁ = 587 MXN/persona\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  R² = 0.523\n```\n\n\n:::\n:::\n\n\n:::\n\n`bedrooms` y `accommodates` correlacionan a 0.88. Por sí sola, `accommodates` ya explica 52% de la variación en precio.\n\n## Dos historias, mismos datos {.smaller}\n\n::: {.incremental}\n**Historia A**: el huésped paga por **espacio físico**. Más recámaras → más espacio → más valor.\n\n**Historia B**: el huésped paga por **capacidad**. Más camas → más gente → la habitación se justifica para grupos → más valor por noche.\n:::\n\n::: {.callout-important appearance=\"minimal\"}\nEl modelo `price ~ bedrooms` **no puede distinguir entre A y B**. Si la verdadera es B, agregar literas o sofá-cama (sin agregar recámara) sería suficiente para subir el precio. Si es A, ese cambio no movería nada.\n\nPatricia no puede decidir invertir en remodelaciones sin esta distinción.\n:::\n\n## Recámaras y capacidad están acopladas {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_regresion_simple_3_files/figure-revealjs/unnamed-chunk-7-1.png){width=1056}\n:::\n:::\n\n\n## \"Controlando por\" — sembrando S7 {.smaller}\n\nLa regresión múltiple permitirá estimar el efecto de `bedrooms` **manteniendo constante** `accommodates`. Esa es la operación técnica de *\"controlando por\"*.\n\n::: {.incremental}\n- Regresión simple actual: *\"deptos con más recámaras tienden a costar más\"*.\n- Regresión múltiple (S7): *\"holding capacity constant, ¿qué efecto adicional tienen las recámaras?\"*.\n- Si el efecto se mantiene → recámaras es palanca real (Historia A).\n- Si el efecto se desvanece → la palanca era capacidad (Historia B).\n:::\n\n::: {.callout-warning appearance=\"minimal\"}\n**No es magia para causalidad.** \"Controlar por\" ajusta por variables **observables**. Si la verdadera causa es algo no medido (decorado, reseñas, ubicación específica), ningún modelo regresivo la captura.\n:::\n\n# Comunicación + cierre {background-color=\"#18BC9C\"}\n\n## Lo que este modelo NO le dice a [Patricia]{.patricia} {.smaller}\n\n::: {.callout-important}\n- **No es una recomendación causal.** No diga *\"agregar recámaras causará +\\$1,329\"*. Diga *\"deptos con más recámaras tienden a costar más\"*.\n- **El rango defendible es ancho por construcción.** Reflejar precisión sobre la **media** del mercado (banda angosta) cuando la pregunta es sobre **un** depto (banda ancha) es engañoso.\n- **No predice fuera del rango muestreado.** Para un caso atípico (estudio de lujo, mansión grande), las predicciones se vuelven poco defendibles.\n- **No incorpora variables clave**: tamaño en m², ubicación específica, amenidades, calidad del host, reseñas. La precisión real está limitada por esas omisiones.\n:::\n\n## Entrega ejecutiva a [Patricia]{.patricia} {.smaller}\n\n::: {.callout-note appearance=\"minimal\"}\n**Para su depto de 2 recámaras en Roma Norte:**\n\n- **Predicción central:** \\$2,413 MXN/noche.\n- **Rango defendible (95%, truncado en 0):** **\\$0 a \\$5,001** MXN/noche. Use ESTE para planeación, no la predicción central sola.\n- **Por qué tan ancho:** el modelo solo conoce el número de recámaras. Hay mucha heterogeneidad en deptos individuales que aún no captura.\n- **Lectura causal:** detectamos un confusor candidato (capacidad, ρ = 0.88 con recámaras). No podemos afirmar que recámaras *cause* el precio sin separar su efecto del de la capacidad.\n- **Recomendación operativa:** no invertir en remodelaciones que agreguen recámaras hasta tener el modelo múltiple. La palanca real podría ser capacidad, no recámaras.\n- **Próxima sesión:** modelo múltiple — separar el efecto de recámaras del de capacidad.\n:::\n\n# Actividad para notebook {background-color=\"#2C3E50\"}\n\n## Lo que harán en su notebook {.smaller}\n\nRepliquen para el depto de Patricia:\n\n1. Cargar el modelo de S5 desde `datos/modelo_s05.rds` (o reconstruirlo idénticamente).\n2. Verificar continuidad con S5: `nrow(roma)` y `coef(modelo)` deben coincidir.\n3. Calcular `predict()` con `interval = \"confidence\"` y con `interval = \"prediction\"` para `bedrooms = 2`.\n4. Comparar los dos rangos: ¿cuántas veces más ancho es uno que el otro?\n5. Visualizar ambas bandas sobre la nube de datos (un solo gráfico).\n6. Calcular `cor(bedrooms, accommodates)` y discutir: ¿qué historia (A o B de la slide) creen que es más probable?\n7. Redactar la **entrega ejecutiva** para Patricia (≈250 palabras), incluyendo: rango defendible, advertencia causal, y por qué necesitamos S7.\n\n# Próxima sesión {background-color=\"#18BC9C\"}\n\n## Lo que llevan hoy {.smaller}\n\n1. Un punto de predicción **sin rango** no es una respuesta operativa.\n2. Hay **dos rangos** distintos. El IC para la media es estrecho; el IC de predicción es ancho. Confundirlos es engañoso.\n3. El IC de predicción **30× más ancho** es el defendible para una decisión individual.\n4. **Extrapolación es teórica**: la aritmética del intervalo no avisa cuando no hay datos.\n5. **Asociación ≠ causa.** Sesgo por variable omitida limita la lectura causal de regresión simple.\n6. **`accommodates` es confusor candidato** del efecto de recámaras (ρ = 0.88). No podemos separar sus efectos sin regresión múltiple.\n\n## Sesión 7 — Regresión múltiple I {.smaller}\n\n> *\"Quiero estimar el precio controlando por varias cosas a la vez.\"*\n\nCerramos el bloque de regresión simple. Lo que viene:\n\n::: {.incremental}\n- Construir modelos con **varias variables** simultáneamente.\n- La operación técnica de *\"controlando por\"*.\n- Cómo cambia (o no) el efecto de `bedrooms` cuando agregamos `accommodates` y otras.\n- Decidir cuáles variables incluir y cuáles no.\n:::\n\n**Sesión 7: Regresión múltiple I — construcción y \"controlando por\".**\n",
    "supporting": [
      "06_regresion_simple_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}