{
  "hash": "cb3b50584e18d5ad44d5ee3129c88209",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Pruebas de hipótesis: comparaciones\"\nsubtitle: \"Sesión 2 · Parcial 3 · Análisis de Datos II\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 2 · 2.2–2.3 Pruebas de una y dos muestras\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Recapitulación {background-color=\"#2C3E50\"}\n\n## La sesión pasada, con [Patricia]{.patricia}\n\nValidamos una afirmación del mercado sobre el precio promedio en Roma Norte usando una **prueba t de una muestra**.\n\nHerramientas que adquirimos:\n\n- $H_0$, $H_1$, $\\alpha$, p-valor\n- Decisión estadística basada en evidencia\n- Comunicación profesional con intervalo de confianza\n\n## Hoy: Patricia tiene más preguntas {.smaller}\n\n> *\"Gracias por aclarar lo de los \\$1,800. Ahora necesito decidir cómo listar. Tres cosas me quitan el sueño:*\n>\n> 1. *¿Cobro más rentando el depto completo o solo un cuarto privado?*\n> 2. *¿Qué tan importante es ser 'superhost' en cuanto a precio?*\n> 3. *¿La proporción de superhosts es similar entre Roma Norte y Condesa?\"*\n\n## Setup del día (igual que S1) {.smaller}\n\nComo la sesión pasada, la idea es que **repliquen en vivo en su notebook**. El pipeline de datos es el mismo de S1 — mismas columnas originales de Inside Airbnb, misma limpieza mínima.\n\n::: {.panel-tabset style=\"font-size: 1.0em;\"}\n\n## 💻 Código\n\n```{.r}\nlibrary(readr)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(scales)\n\n# Mismo csv de S1: si ya lo tienen cargado en su notebook, no hace\n# falta volver a descargar. Si es una sesión nueva, córranlo otra vez.\nurl <- paste0(\n  \"https://data.insideairbnb.com/mexico/df/mexico-city/\",\n  \"2025-09-27/data/listings.csv.gz\"\n)\n\nlistings <- read_csv(url, show_col_types = FALSE) |>\n  mutate(price = parse_number(price)) |>\n  filter(!is.na(price))\n\n# Subsets de esta sesión\nroma_norte  <- listings |> filter(host_neighbourhood == \"Roma Norte\")\nroma_prop   <- roma_norte |> filter(room_type == \"Entire home/apt\")\nroma_cuarto <- roma_norte |> filter(room_type == \"Private room\")\ncondesa     <- listings |> filter(host_neighbourhood == \"Condesa\")\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nlistings       : 23,567 filas\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nroma_norte     : 1,183 filas (todas las habitaciones)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nroma_prop      : 983 filas (Entire home/apt)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nroma_cuarto    : 188 filas (Private room)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncondesa        : 762 filas\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-note appearance=\"minimal\"}\n**Recordatorio del diccionario (S1)**: `host_neighbourhood` es la *colonia* reportada por el host, `room_type` el tipo de habitación (`Entire home/apt`, `Private room`, ...), `host_is_superhost` es lógica (`TRUE`/`FALSE`/`NA`).\n:::\n\n# Tabla de decisión {background-color=\"#18BC9C\"}\n\n## ¿Qué prueba usar? {.smaller}\n\nCada pregunta requiere una prueba distinta. **La primera decisión no es cuál prueba — es cuál pregunta.**\n\n| Situación | Pregunta | Prueba |\n|:---|:---|:---|\n| Una muestra, una media | ¿μ = valor fijo? | t una muestra *(S1)* |\n| Una muestra, una proporción | ¿p = valor fijo? | z una proporción |\n| Dos grupos independientes, medias | ¿μ₁ = μ₂? | t dos muestras |\n| Dos grupos independientes, proporciones | ¿p₁ = p₂? | z dos proporciones |\n| Mediciones pareadas | ¿μdif = 0? | t pareada |\n\n## El patrón común\n\nTodas estas pruebas siguen **el mismo framework** de la sesión 1:\n\n1. Traducir pregunta de negocio → $H_0$, $H_1$\n2. Elegir nivel de significancia $\\alpha$\n3. Verificar supuestos\n4. Ejecutar la prueba\n5. Interpretar en contexto de negocio\n\nCambia el estadístico; no el pensamiento.\n\n# Pregunta 1: Completo vs. Cuarto {background-color=\"#2C3E50\"}\n\n## La pregunta de Patricia\n\n> \"¿Cobro más rentando el depto completo o solo un cuarto privado?\"\n\nTraducción analítica:\n\n$$H_0: \\mu_{completo} = \\mu_{cuarto}$$\n$$H_1: \\mu_{completo} \\neq \\mu_{cuarto}$$\n\n**Dos muestras independientes** porque son dos grupos de propiedades diferentes.\n\n## Exploración de los dos grupos {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nroma_norte |>\n  filter(room_type %in% c(\"Entire home/apt\", \"Private room\")) |>\n  group_by(room_type) |>\n  summarise(\n    n        = n(),\n    media    = mean(price),\n    mediana  = median(price),\n    desv_est = sd(price)\n  )\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Tipo            |   n| Media| Mediana| Desv. est.|\n|:---------------|---:|-----:|-------:|----------:|\n|Entire home/apt | 983| 2,111|   1,493|      3,193|\n|Private room    | 188|   849|     594|        771|\n\n\n:::\n:::\n\n\n:::\n\n## Visualización de la comparación {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nroma_norte |>\n  filter(room_type %in% c(\"Entire home/apt\", \"Private room\")) |>\n  ggplot(aes(x = room_type, y = price,\n             fill = room_type)) +\n  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +\n  scale_y_continuous(labels = label_comma(),\n                     limits = c(0, 5000)) +\n  scale_fill_manual(values = c(\"#18BC9C\", \"#3498DB\")) +\n  labs(x = NULL, y = \"Precio (MXN por noche)\",\n       title = \"Precio por tipo en Roma Norte\") +\n  theme(legend.position = \"none\")\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_pruebas_dos_muestras_files/figure-html/unnamed-chunk-3-1.png){width=864}\n:::\n:::\n\n\n:::\n\n## Un detalle crítico: ¿varianzas iguales?\n\nLa prueba t de dos muestras tiene dos variantes:\n\n- **Welch** (default en R): no supone varianzas iguales\n- **Pooled** (`var.equal = TRUE`): supone varianzas iguales\n\n::: {.callout-important}\n**Usa Welch por default.** Es más robusta y casi siempre apropiada. El pooled es una optimización que rara vez vale la pena en la práctica.\n:::\n\n## Ejecución de la prueba {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nt.test(\n  price ~ room_type,\n  data = roma_norte |>\n    filter(room_type %in%\n           c(\"Entire home/apt\", \"Private room\")),\n  alternative = \"two.sided\",\n  conf.level  = 0.95\n)\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  price by room_type\nt = 10.847, df = 1123.8, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Entire home/apt and group Private room is not equal to 0\n95 percent confidence interval:\n 1033.551 1490.019\nsample estimates:\nmean in group Entire home/apt    mean in group Private room \n                    2110.6785                      848.8936 \n```\n\n\n:::\n:::\n\n\n:::\n\n## Interpretación para Patricia {.smaller}\n\nPlantilla profesional:\n\n::: {.callout-note appearance=\"minimal\"}\n**Hallazgo.** Comparamos 983 propiedades completas contra 188 cuartos privados listados en Roma Norte. La media de la propiedad completa es **\\$2,111 MXN/noche** vs. **\\$849 MXN/noche** del cuarto privado — una diferencia de aproximadamente **\\$1,262** (p = <2e-16). La diferencia es estadísticamente significativa.\n\n**Traducción a decisión.** Su depto de 2 recámaras, listado completo, cobra *en promedio* una cantidad sensiblemente mayor que si lo divide en cuartos privados. Sin embargo, la decisión de negocio depende también de: ocupación esperada en cada modalidad, costos operativos, y sus preferencias personales sobre compartir espacio.\n\n**Lo que este análisis NO dice**: cuál modalidad deja más ingreso total anual. Precio × ocupación es una cuenta distinta que veremos más adelante.\n:::\n\n# Pregunta 2: Superhost {background-color=\"#18BC9C\"}\n\n## Primera parte: ¿qué proporción del mercado?\n\nAntes de preguntarse \"¿debo ser superhost?\", Patricia quiere saber:\n\n> \"¿Qué proporción del mercado en Roma Norte son superhosts?\"\n\nEsto es una **prueba de una proporción**: $H_0: p = 0.30$ (una referencia plausible \"a priori\" — un tercio del mercado). La prueba nos dirá si la proporción real difiere significativamente de esa referencia.\n\n## Ejecución: una proporción {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\n# Contar superhosts en Roma Norte\n# host_is_superhost es lógica (TRUE / FALSE / NA)\nconteo <- roma_norte |>\n  count(host_is_superhost) |>\n  mutate(prop = n / sum(n))\n\nprint(conteo)\n\n# Prueba: ¿la proporción es igual a 0.30?\nn_super <- sum(roma_norte$host_is_superhost, na.rm = TRUE)\nn_total <- sum(!is.na(roma_norte$host_is_superhost))\n\nprop.test(x = n_super, n = n_total, p = 0.30,\n          alternative = \"two.sided\")\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|host_is_superhost |   n| Proporción|\n|:-----------------|---:|----------:|\n|FALSE             | 373|      0.315|\n|TRUE              | 589|      0.498|\n|NA                | 221|      0.187|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  n_super out of n_total, null probability 0.3\nX-squared = 445.2, df = 1, p-value < 2.2e-16\nalternative hypothesis: true p is not equal to 0.3\n95 percent confidence interval:\n 0.5805633 0.6430608\nsample estimates:\n        p \n0.6122661 \n```\n\n\n:::\n:::\n\n\n:::\n\n## Segunda parte: ¿los superhosts cobran más? {.smaller}\n\nAhora la pregunta de fondo:\n\n$$H_0: \\mu_{superhost} = \\mu_{no\\_super}$$\n$$H_1: \\mu_{superhost} \\neq \\mu_{no\\_super}$$\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nt.test(\n  price ~ host_is_superhost,\n  data = roma_prop |> filter(!is.na(host_is_superhost)),\n  alternative = \"two.sided\"\n)\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  price by host_is_superhost\nt = -0.17278, df = 294.33, p-value = 0.8629\nalternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0\n95 percent confidence interval:\n -731.1632  613.1446\nsample estimates:\nmean in group FALSE  mean in group TRUE \n           2081.502            2140.511 \n```\n\n\n:::\n:::\n\n\n:::\n\n## Advertencia crítica sobre la interpretación {.smaller}\n\nObservamos: superhost \\$2,141 MXN/noche vs. no-superhost \\$2,082 MXN/noche (diferencia ≈ \\$59, p = 0.863).\n\n::: {.callout-warning}\nQue la prueba diga que los superhosts cobran más **NO significa que ser superhost cause un precio mayor**. Puede ser que los hosts con propiedades mejores (más grandes, mejor ubicadas) tengan más probabilidad de volverse superhosts.\n\nEsta es la distinción **correlación vs. causalidad** que retomaremos en regresión múltiple (sesión 7). Por ahora, lo honesto es decir: \"los superhosts están asociados con precios mayores\".\n:::\n\n# Pregunta 3: Dos proporciones {background-color=\"#2C3E50\"}\n\n## Comparar proporciones entre alcaldías\n\n> \"¿La proporción de superhosts es similar entre Roma Norte y Condesa?\"\n\n$$H_0: p_{Roma} = p_{Condesa}$$\n$$H_1: p_{Roma} \\neq p_{Condesa}$$\n\nAquí estamos comparando dos proporciones poblacionales → `prop.test()` con dos argumentos.\n\n## Ejecución {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\n# Conteos en cada zona\nresumen <- listings |>\n  filter(host_neighbourhood %in% c(\"Roma Norte\", \"Condesa\")) |>\n  group_by(host_neighbourhood) |>\n  summarise(\n    n_super = sum(host_is_superhost, na.rm = TRUE),\n    n_total = sum(!is.na(host_is_superhost))\n  )\n\nprint(resumen)\n\n# Prueba de diferencia de proporciones\nprop.test(\n  x = resumen$n_super,\n  n = resumen$n_total,\n  alternative = \"two.sided\"\n)\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Colonia    | Superhosts| Total| Proporción|\n|:----------|----------:|-----:|----------:|\n|Condesa    |        313|   681|      0.460|\n|Roma Norte |        589|   962|      0.612|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  resumen$n_super out of resumen$n_total\nX-squared = 36.911, df = 1, p-value = 1.237e-09\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.2023683 -0.1029275\nsample estimates:\n   prop 1    prop 2 \n0.4596182 0.6122661 \n```\n\n\n:::\n:::\n\n\n:::\n\n# Datos pareados {background-color=\"#18BC9C\"}\n\n## Cuándo usar una prueba pareada {.smaller}\n\nLas pruebas vistas hasta ahora comparan **grupos independientes**. En algunos casos, cada observación aparece **dos veces** y queremos medir el cambio:\n\n- Examen antes vs. después de un curso, aplicado a los mismos alumnos\n- Ventas del mismo local en dos trimestres consecutivos\n- Presión arterial antes y después de un tratamiento, mismo paciente\n\nEn estos casos, los datos están **pareados** y la prueba independiente sería incorrecta.\n\n## El caso pareado en Airbnb {.smaller}\n\nEn el dataset de Airbnb no tenemos pares naturales: cada listing es una observación única. Por eso esta prueba **no aplica directamente a Patricia hoy**, pero conviene entenderla.\n\nUn ejemplo hipotético: si midiéramos el precio de los **mismos 100 listings** en enero y en julio, tendríamos datos pareados y preguntaríamos:\n\n$$H_0: \\mu_{diferencia} = 0$$\n$$H_1: \\mu_{diferencia} \\neq 0$$\n\n## Sintaxis en R (referencia) {.smaller}\n\n```{.r}\n# Supongamos precio_enero y precio_julio de los mismos listings\nt.test(\n  precio_julio, precio_enero,\n  paired = TRUE,\n  alternative = \"two.sided\"\n)\n```\n\nLa clave es el argumento `paired = TRUE`. Con eso R calcula las diferencias dentro de cada par y prueba si su media es cero.\n\n# Cierre {background-color=\"#2C3E50\"}\n\n## Lo que aprendió Patricia hoy {.smaller}\n\n1. **Rentar completo vs. cuarto**: diferencia ≈ \\$1,262 MXN/noche a favor de la propiedad completa (p = <2e-16).\n2. **Superhost y mercado**: 61% del mercado en Roma Norte son superhosts; los superhosts cobran ≈ \\$59 más por noche (p = 0.863).\n3. **Roma vs. Condesa**: 61% vs. 46% superhosts; la diferencia sí es estadísticamente significativa (p = 1.24e-09).\n\nCada conclusión vino acompañada de advertencias honestas sobre lo que los datos **no** responden.\n\n## Lo que las pruebas de hoy NO resuelven {.smaller}\n\n::: {.callout-important}\nLas comparaciones de hoy son **una-variable-a-la-vez**. Eso es útil pero limitado: en la realidad, muchas cosas cambian al mismo tiempo.\n\nEjemplo: si descubrimos que los superhosts cobran más, ¿es por ser superhost, o porque las propiedades de superhosts son diferentes (tamaño, ubicación)? No podemos saberlo con las pruebas de hoy.\n\nPara esto necesitaremos la **regresión** (sesiones 5–7), que permite \"controlar\" por otras variables.\n:::\n\n## Actividad para su notebook {.smaller}\n\nEn su notebook `.ipynb`, repliquen:\n\n1. La comparación entre propiedad completa y cuarto privado en Roma Norte.\n2. La comparación de precio entre superhost y no-superhost.\n3. La comparación de proporciones entre Roma y una alcaldía de su elección.\n\nEntregable: una celda de markdown por cada prueba con el formato de comunicación profesional visto en clase.\n\n## Preview de la próxima sesión {.smaller}\n\nPatricia regresa con una pregunta que **amplifica** las de hoy:\n\n> *\"Tres pruebas de dos grupos está bien, pero yo quiero comparar Roma, Condesa, Polanco y Del Valle **a la vez**. ¿Y si el tipo de propiedad se asocia con la política de cancelación?\"*\n\nComparar **más de dos grupos** → **ANOVA**.\nAsociar **dos variables categóricas** → **χ²**.\n\n**Sesión 3: ANOVA y chi-cuadrada.**\n",
    "supporting": [
      "02_pruebas_dos_muestras_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}