{
  "hash": "0b284b2f3a47068b601a48ceab34fe9d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión simple I: del problema al modelo\"\nsubtitle: \"Sesión 4 · Parcial 3 · Análisis de Datos II\"\nauthor: \"CJJM\"\ndate: today\ndate-format: \"D [de] MMMM, YYYY\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    logo: ../../assets/img/logo.png\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos II — Sesión 4 · 5.1 Modelo lineal · 5.7 Aplicaciones con R\"\n    incremental: false\n    fig-align: center\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Recapitulación {background-color=\"#2C3E50\"}\n\n## Lo que llevamos con [Patricia]{.patricia} {.smaller}\n\n**Sesión 1** — El artículo decía \\$1,800. Lo validamos con una prueba **t de una muestra** y descubrimos que no era creíble.\n\n**Sesión 2** — Comparamos pares: completo vs. cuarto, superhost vs. no. Pruebas **t y de proporciones**.\n\n**Sesión 3** — Comparamos 4 zonas a la vez (**ANOVA**) y la composición del mercado (**χ²**).\n\nEn las tres sesiones, la lógica fue *comparar*: ¿este grupo es distinto de aquel? ¿esta media es igual a esa? Hoy damos un salto.\n\n## Hoy: Patricia necesita un número concreto {.smaller}\n\n> *\"Comparar zonas y tipos me sirvió, pero ahora necesito una respuesta más concreta: dado mi depto de 2 recámaras en Roma Norte, ¿qué precio debo cobrar por noche? Quiero un modelo que me dé un número, no solo comparaciones.\"*\n\n::: {.callout-note}\nEl paso de \"comparar grupos\" a \"modelar relaciones\" es **el cambio de paradigma central del curso**. Las pruebas de hipótesis preguntan *¿hay diferencia?*. El modelo de regresión pregunta *¿cuánto?* y *¿qué espero para un caso nuevo?*\n:::\n\n# De comparar a modelar {background-color=\"#18BC9C\"}\n\n## Lo que hicimos vs. lo que necesitamos {.smaller}\n\n| Sesiones 1-3 | Sesión 4 en adelante |\n|:---|:---|\n| ¿Es el promedio \\$1,800? | ¿Cuánto debería cobrar Patricia? |\n| ¿Roma ≠ Condesa? | ¿En cuánto cambia el precio por cada recámara? |\n| Comparar **grupos** | Predecir un **valor** |\n| Respuesta: sí/no + p-valor | Respuesta: **un número** + su incertidumbre |\n\nEl instrumento: **regresión lineal simple** — un modelo que relaciona una variable de respuesta (precio) con una variable predictora (recámaras).\n\n## La intuición visual {.smaller}\n\nAntes de fórmulas o código, veamos los datos.\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.40em;\"}\n```{.r}\nroma <- listings |>\n  filter(host_neighbourhood == \"Roma Norte\",\n         room_type == \"Entire home/apt\",\n         !is.na(bedrooms))\n\nggplot(roma, aes(x = bedrooms, y = price)) +\n  geom_jitter(width = 0.15, alpha = 0.3,\n              color = \"#18BC9C\") +\n  scale_y_continuous(labels = label_comma()) +\n  scale_x_continuous(breaks = 0:9) +\n  labs(x = \"Recámaras\", y = \"Precio (MXN/noche)\",\n       title = \"Precio vs. recámaras en Roma Norte\")\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04_regresion_simple_1_files/figure-revealjs/unnamed-chunk-1-1.png){width=864}\n:::\n:::\n\n\n:::\n\nA simple vista: más recámaras → precios más altos. ¿Podemos cuantificar esa tendencia?\n\n## ¿Qué es \"la recta de mejor ajuste\"? {.smaller}\n\nLa idea de la regresión lineal simple es trazar **una recta** que resuma la tendencia general de la nube de puntos.\n\n$$\\hat{y} = \\beta_0 + \\beta_1 \\, x$$\n\n- $\\hat{y}$ = precio **estimado** (no observado, sino predicho por el modelo)\n- $x$ = número de recámaras\n- $\\beta_0$ = **intercepto** (valor estimado cuando $x = 0$)\n- $\\beta_1$ = **pendiente** (cambio en $\\hat{y}$ por cada unidad de aumento en $x$)\n\n::: {.callout-note appearance=\"minimal\"}\nR encuentra los valores de $\\beta_0$ y $\\beta_1$ que **minimizan la suma de las distancias verticales al cuadrado** entre cada punto y la recta. Este método se llama *mínimos cuadrados ordinarios* (OLS). No necesitamos calcularlos a mano — `lm()` lo hace.\n:::\n\n# Construcción del modelo {background-color=\"#2C3E50\"}\n\n## Los datos: precio por recámaras {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nroma |>\n  group_by(bedrooms) |>\n  summarise(\n    n       = n(),\n    media   = mean(price),\n    mediana = median(price),\n    de      = sd(price)\n  )\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Recámaras|   n|  Media| Mediana|    DE|\n|---------:|---:|------:|-------:|-----:|\n|         0|  36|  1,508|   1,262|   763|\n|         1| 458|  1,510|   1,272| 3,758|\n|         2| 343|  1,880|   1,600| 1,051|\n|         3|  96|  2,981|   2,582| 1,390|\n|         4|  22|  6,032|   5,469| 2,473|\n|         5|  10|  6,831|   6,099| 3,348|\n|         6|   7|  9,711|  10,562| 2,802|\n|         7|   7| 13,848|  15,756| 5,466|\n|         9|   2| 14,302|  14,302| 4,697|\n\n\n:::\n:::\n\n\n:::\n\nLa mayoría de los listings tienen 1 o 2 recámaras (82% del total). La media crece consistentemente con el número de recámaras.\n\n## Ajuste del modelo con `lm()` {.smaller}\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\nmodelo <- lm(price ~ bedrooms, data = roma)\nsummary(modelo)\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = price ~ bedrooms, data = roma)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -3324   -850   -173    309  79800 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -81.35     170.00  -0.479    0.632    \nbedrooms     1281.08      83.64  15.317   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2872 on 979 degrees of freedom\nMultiple R-squared:  0.1933,\tAdjusted R-squared:  0.1925 \nF-statistic: 234.6 on 1 and 979 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n\n## Lectura del output de `summary()` {.smaller}\n\nEl output tiene muchas líneas. Por ahora nos interesan **solo tres cosas**:\n\n1. **(Intercept)** — fila `Estimate`: es $\\beta_0$\n2. **bedrooms** — fila `Estimate`: es $\\beta_1$\n3. **Signif. codes** — los asteriscos dan una primera señal de si el efecto es estadísticamente significativo\n\n::: {.callout-warning appearance=\"minimal\"}\nEl R², los errores estándar, los p-valores de cada coeficiente y el F global **los veremos con calma en S5**. Hoy nos concentramos en la ecuación y su interpretación.\n:::\n\n# Lectura de coeficientes {background-color=\"#18BC9C\"}\n\n## La ecuación estimada\n\nCon los datos de 981 propiedades completas en Roma Norte:\n\n$$\\widehat{\\text{precio}} = -81 + 1,281 \\times \\text{recámaras}$$\n\nDos coeficientes, dos interpretaciones.\n\n## β₀: el intercepto {.smaller}\n\n$$\\beta_0 = -81 \\text{ MXN}$$\n\nEs el precio estimado cuando `recámaras = 0`. En este caso, **un precio negativo no tiene sentido físico** — nadie paga $-81 por noche.\n\n¿Por qué sale ese número? Porque la recta de mejor ajuste **no está obligada a pasar por valores razonables fuera del rango de los datos**. El intercepto es un parámetro técnico que posiciona la recta, no una predicción real.\n\n::: {.callout-important}\n**Regla general sobre el intercepto.** A veces tiene interpretación sustantiva (si $x = 0$ es una situación real y hay datos en esa zona). A veces es solo un ajuste matemático. Siempre hay que preguntarse: *\"¿tiene sentido práctico pensar en $x = 0$?\"*. Aquí no: un depto con 0 recámaras, estrictamente, no existe como concepto en el dataset (los 36 estudios tienen `bedrooms = 0` en el csv, pero son un caso límite).\n:::\n\n## β₁: la pendiente {.smaller}\n\n$$\\beta_1 = 1,281 \\text{ MXN por recámara}$$\n\nInterpretación directa: **por cada recámara adicional**, el precio esperado por noche **aumenta en ~\\$1,281**.\n\nEsto es el corazón del modelo: una regla cuantitativa que convierte una característica de la propiedad en una estimación de precio.\n\n::: {.callout-warning}\n**Asociación, no causalidad.** Que el modelo diga \"+\\$1,281 por recámara\" **no significa** que agregar una recámara a un depto cause un aumento de \\$1,281. Puede ser que los deptos con más recámaras sean más grandes, mejor ubicados, o de hosts más profesionales — y sean *esas* características las que expliquen el precio más alto.\n\nLa distinción entre asociación y causalidad es tema central de la **Sesión 6**. Por ahora: todo lo que sale de este modelo es asociación.\n:::\n\n## Aplicación al depto de [Patricia]{.patricia} {.smaller}\n\nPatricia tiene un depto de **2 recámaras**. Sustituyendo:\n\n$$\\widehat{\\text{precio}} = -81 + 1,281 \\times 2 = 2,481 \\text{ MXN/noche}$$\n\n::: {.panel-tabset style=\"font-size: 1.20em;\"}\n\n## 💻 Código\n\n```{.r}\npredict(modelo, newdata = data.frame(bedrooms = 2))\n```\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n       1\n2,481\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-note appearance=\"minimal\"}\nComparación con referencias previas: en S1 dijimos que la mediana del mercado era ~\\$1,492. Ahora, condicionando en 2 recámaras, el modelo estima **\\$2,481** — un número más alto y más específico para su propiedad.\n:::\n\n# Visualización del modelo {background-color=\"#2C3E50\"}\n\n## Recta ajustada sobre los datos {.smaller}\n\n::: {.panel-tabset}\n\n## 💻 Código\n\n::: {style=\"font-size: 1.20em;\"}\n```{.r}\nggplot(roma, aes(x = bedrooms, y = price)) +\n  geom_jitter(width = 0.15, alpha = 0.3,\n              color = \"#18BC9C\") +\n  geom_smooth(method = \"lm\", se = FALSE,\n              color = \"#2C3E50\", linewidth = 1.2) +\n  scale_y_continuous(labels = label_comma()) +\n  scale_x_continuous(breaks = 0:9) +\n  labs(x = \"Recámaras\", y = \"Precio (MXN/noche)\",\n       title = \"Modelo: precio ~ recámaras\")\n```\n:::\n\n## 📊 Resultado\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04_regresion_simple_1_files/figure-revealjs/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n\n:::\n\nEl punto rojo es la predicción para el depto de Patricia. La recta captura la tendencia general, pero hay **mucha dispersión** alrededor de ella — muchos puntos están lejos de la línea.\n\n## Lo que este modelo NO le dice a [Patricia]{.patricia} {.smaller}\n\n::: {.callout-important}\nEl modelo nos dio un número (\\$2,481), pero **un número sin contexto de calidad es peligroso**:\n\n- **No sabemos qué tan preciso es.** ¿El margen de error es \\$200 o \\$2,000? Sin eso, la estimación no sirve para planear.\n- **No sabemos si el modelo es válido.** Asume una relación lineal y otras condiciones técnicas que no hemos verificado.\n- **Solo usa una variable.** El precio seguramente depende de más cosas (tamaño, amenidades, ubicación exacta, reseñas). Usar solo recámaras es una simplificación deliberada para aprender.\n- **No dice nada sobre causalidad.** La asociación recámaras → precio no implica que agregar recámaras aumente el precio.\n\nCada una de estas limitaciones se resuelve en las próximas sesiones.\n:::\n\n# Actividad para notebook {background-color=\"#2C3E50\"}\n\n## Lo que harán en su notebook {.smaller}\n\nRepliquen el análisis en su propio `.ipynb`:\n\n1. Filtrar Roma Norte, propiedad completa, `bedrooms` no faltante.\n2. Diagrama de dispersión de `price` vs `bedrooms`.\n3. Ajustar el modelo: `lm(price ~ bedrooms, data = roma)`.\n4. Extraer β₀ y β₁ e interpretar cada uno en una oración.\n5. Usar `predict()` para estimar el precio de un depto de 2 recámaras.\n6. Redactar un **párrafo profesional** (máximo 150 palabras) para Patricia que incluya: la estimación, qué significa, y al menos una advertencia honesta sobre las limitaciones.\n\n# Cierre {background-color=\"#18BC9C\"}\n\n## Lo que llevan hoy {.smaller}\n\n1. El **cambio de paradigma**: de comparar grupos (pruebas de hipótesis) a **modelar relaciones** (regresión).\n2. La ecuación del modelo lineal simple: $\\hat{y} = \\beta_0 + \\beta_1 x$.\n3. Cómo ajustar un modelo en R con `lm()` y leer el output básico.\n4. Interpretación de los coeficientes: qué significan β₀ y β₁ **en contexto de negocio**.\n5. Cómo obtener una predicción con `predict()`.\n6. Que un modelo que da un número **no es automáticamente un buen modelo** — hay que verificarlo.\n\n## Para la próxima sesión {.smaller}\n\nTenemos un modelo y una predicción: **\\$2,481 MXN/noche** para el depto de Patricia. Pero:\n\n- ¿Es **confiable** ese número?\n- ¿Los **supuestos** del modelo se cumplen?\n- ¿Qué tan bien **explica** los datos?\n- ¿Cómo sabemos si el modelo está **mal**?\n\n**Sesión 5: Regresión simple II — validez, supuestos, diagnóstico.**\n",
    "supporting": [
      "04_regresion_simple_1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}